window.SITE_I18N = {
  en: {
    title: "Lumen — light, held still",
    desc: "Fictional photographer. A cinematic lookbook. Work, about, contact on one canvas.",
    skip: "Skip to work",
    lang: "Language",
    modes: "Studio modes",
    edit: "Edit",
    about: "About",
    contact: "Contact",
    tag: "Photographs for rooms that already know what they want.",
    meta: "Lisboa · analog &amp; available light",
    aboutTitle: "Held still.",
    about1: "Lumen is a fictional studio. The work is hospitality, quiet portraits, and rooms that keep their own time. Commissioned from Lisboa. Travels when the light is worth it.",
    about2: "No kits. No presets named after cities. One camera, one window, one long lunch after the sitting.",
    selected: "Selected",
    selectedV: "Hotels, kitchens, private houses",
    format: "Format",
    formatV: "Digital + 120",
    books: "Books",
    booksV: "On request",
    write: "Write first.",
    writeLede: "A date, a room, what the pictures are for. This form stays on the page — a live job would reach the studio inbox.",
    name: "Name",
    email: "Email",
    sitting: "The sitting",
    send: "Send",
    formOk: "Received. The studio would write back from a live inbox.",
    demo: "Demo notice",
    demoLink: "I build sites like this",
    catHospitality: "Hospitality",
    catPortrait: "Portrait",
    catArchitecture: "Architecture",
    catLandscape: "Landscape",
    catStill: "Still"
  },
  pt: {
    title: "Lumen — luz, parada",
    desc: "Fotógrafo de ficção. Um lookbook de cinema. Trabalho, sobre e contacto num só ecrã.",
    skip: "Saltar para o trabalho",
    lang: "Idioma",
    modes: "Modos do estúdio",
    edit: "Obra",
    about: "Sobre",
    contact: "Contacto",
    tag: "Fotografias para salas que já sabem o que querem.",
    meta: "Lisboa · analógico e luz disponível",
    aboutTitle: "Parada.",
    about1: "A Lumen é um estúdio de ficção. O trabalho é hospitalidade, retratos quietos e casas com o seu próprio tempo. Encomendas a partir de Lisboa. Viaja quando a luz vale a pena.",
    about2: "Sem kits. Sem predefinições com nomes de cidades. Uma câmara, uma janela, um almoço longo depois da sessão.",
    selected: "Escolhido",
    selectedV: "Hotéis, cozinhas, casas privadas",
    format: "Formato",
    formatV: "Digital + 120",
    books: "Livros",
    booksV: "A pedido",
    write: "Escreva primeiro.",
    writeLede: "Uma data, uma sala, para que servem as fotos. Este formulário fica na página — um trabalho a sério iria para o e-mail do estúdio.",
    name: "Nome",
    email: "E-mail",
    sitting: "A sessão",
    send: "Enviar",
    formOk: "Recebido. O estúdio responderia a partir de um e-mail a sério.",
    demo: "Aviso de demo",
    demoLink: "Faço sites assim",
    catHospitality: "Hospitalidade",
    catPortrait: "Retrato",
    catArchitecture: "Arquitectura",
    catLandscape: "Paisagem",
    catStill: "Natureza-morta"
  }
};

I18N.start(window.SITE_I18N);
