window.SITE_I18N = {
  en: {
    "title.home": "Lumen — photography by Clara Ventura",
    "desc.home": "Fictional photography studio in Lisboa: portraits, weddings, spaces, food and travel.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    navWork: "Work",
    navStudio: "Studio",
    navSessions: "Sessions",
    navEnquire: "Enquire",
    heroAria: "Featured photographs",
    kicker: "Clara Ventura · photographer · Lisboa",
    heroTitle: "Light, <em>kept.</em>",
    scrollCue: "Scroll to develop",
    seriesLabel: "Five series",
    seriesTitle: "Series",
    frames: "{n} frames",
    tableTitle: "The light table",
    filterAria: "Filter by series",
    all: "All",
    "s.portraits": "Portraits",
    "s.weddings": "Weddings",
    "s.spaces": "Spaces",
    "s.table": "Table",
    "s.away": "Away",
    "sd.portraits": "Faces in window light",
    "sd.weddings": "The day, not the poses",
    "sd.spaces": "Rooms and the buildings around them",
    "sd.table": "Food before the first bite",
    "sd.away": "Roads, lakes and weather",
    open: "Open",
    lightboxAria: "Photograph",
    close: "Close",
    prev: "Previous",
    next: "Next",
    loupeHint: "Hover to look closer",
    studioLabel: "The studio",
    studioTitle: "Patient pictures for people, places and plates.",
    studioP1: "I work with daylight first and a single lamp when I must. Sessions are slow on purpose: you forget the camera, and the pictures start to look like you.",
    studioP2: "Every gallery is edited by hand, delivered in two weeks and kept for a year.",
    studioAlt: "A camera and two lenses on a dark table",
    statYears: "Years behind the lens",
    statSessions: "Sessions last year",
    statDays: "Days to your gallery",
    sessionsLabel: "Sessions",
    sessionsTitle: "Pick a light to work in",
    from: "from",
    choose: "Check a date",
    enquireLabel: "Enquire",
    enquireTitle: "Check a date",
    enquireText: "Tell me the day and the kind of session. I answer every message within two working days.",
    fSession: "Session",
    fDate: "Date",
    fName: "Name",
    fEmail: "Email",
    fMessage: "What do you have in mind?",
    send: "Send enquiry",
    dateFree: "{date} is free.",
    dateTaken: "{date} is taken. Nearest free day: {next}.",
    datePast: "Please pick a day from today on.",
    errName: "Please add your name.",
    errEmail: "Please add an email I can answer.",
    sent: "Thank you, {name} — your enquiry for {date} is noted. (Demo: nothing was sent.)",
    footerLine: "A fictional studio. Photographs from Unsplash.",
    backAtelier: "Made by Atelier",
    months: "January,February,March,April,May,June,July,August,September,October,November,December"
  },
  pt: {
    "title.home": "Lumen — fotografia de Clara Ventura",
    "desc.home": "Estúdio de fotografia fictício em Lisboa: retratos, casamentos, espaços, comida e viagens.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    navWork: "Trabalho",
    navStudio: "Estúdio",
    navSessions: "Sessões",
    navEnquire: "Contacto",
    heroAria: "Fotografias em destaque",
    kicker: "Clara Ventura · fotógrafa · Lisboa",
    heroTitle: "Luz, <em>guardada.</em>",
    scrollCue: "Faça scroll para revelar",
    seriesLabel: "Cinco séries",
    seriesTitle: "Séries",
    frames: "{n} fotogramas",
    tableTitle: "A mesa de luz",
    filterAria: "Filtrar por série",
    all: "Todas",
    "s.portraits": "Retratos",
    "s.weddings": "Casamentos",
    "s.spaces": "Espaços",
    "s.table": "Mesa",
    "s.away": "Fora",
    "sd.portraits": "Rostos à luz da janela",
    "sd.weddings": "O dia, não as poses",
    "sd.spaces": "Divisões e os edifícios à volta",
    "sd.table": "Comida antes da primeira dentada",
    "sd.away": "Estradas, lagos e tempo",
    open: "Abrir",
    lightboxAria: "Fotografia",
    close: "Fechar",
    prev: "Anterior",
    next: "Seguinte",
    loupeHint: "Passe o rato para ver de perto",
    studioLabel: "O estúdio",
    studioTitle: "Fotografias pacientes de pessoas, lugares e pratos.",
    studioP1: "Trabalho primeiro com luz natural e com um só candeeiro quando é preciso. As sessões são lentas de propósito: esquece-se da câmara e as fotografias começam a parecer-se consigo.",
    studioP2: "Cada galeria é editada à mão, entregue em duas semanas e guardada durante um ano.",
    studioAlt: "Uma câmara e duas objetivas numa mesa escura",
    statYears: "Anos atrás da câmara",
    statSessions: "Sessões no último ano",
    statDays: "Dias até à sua galeria",
    sessionsLabel: "Sessões",
    sessionsTitle: "Escolha a luz em que quer trabalhar",
    from: "desde",
    choose: "Ver datas",
    enquireLabel: "Contacto",
    enquireTitle: "Ver uma data",
    enquireText: "Diga-me o dia e o tipo de sessão. Respondo a todas as mensagens em dois dias úteis.",
    fSession: "Sessão",
    fDate: "Data",
    fName: "Nome",
    fEmail: "Email",
    fMessage: "O que tem em mente?",
    send: "Enviar pedido",
    dateFree: "{date} está livre.",
    dateTaken: "{date} está ocupado. Dia livre mais próximo: {next}.",
    datePast: "Escolha um dia a partir de hoje.",
    errName: "Indique o seu nome.",
    errEmail: "Indique um email para eu responder.",
    sent: "Obrigada, {name} — o seu pedido para {date} ficou registado. (Demo: nada foi enviado.)",
    footerLine: "Um estúdio fictício. Fotografias do Unsplash.",
    backAtelier: "Feito pelo Atelier",
    months: "janeiro,fevereiro,março,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro"
  }
};

I18N.start(window.SITE_I18N);
