window.SITE_I18N = {
  en: {
    "title.home": "Atelier Moura — bespoke tailoring in Lisboa",
    "desc.home": "Fictional bespoke tailor on Rua dos Fanqueiros. Design your jacket live, choose the cloth, and book a fitting.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    logoSub: "Tailors · Lisboa",
    navDesign: "Design",
    navProcess: "Process",
    navCloth: "Cloth",
    navFitting: "Fittings",
    bookCta: "Book a fitting",
    kicker: "Rua dos Fanqueiros · since 1987",
    heroTitle: "Cut for one person. <em>Sewn by hand.</em>",
    heroLede: "A paper pattern drawn from your measurements, a jacket basted and fitted on you twice, and about sixty hours of hand work. Start by drawing it below.",
    heroCta: "Design your jacket",
    heroHow: "How it's made",
    f1: "Hand stitches",
    f2: "Fittings",
    f3: "Weeks",
    heroAlt: "Hands smoothing a grey wool jacket on the cutting table",
    heroCap: "Cutting table, second floor",
    designKicker: "The designer",
    designTitle: "Draw your jacket",
    designLede: "Every choice redraws the jacket and the price. Nothing here is a template: it's what we'd chalk on the cloth.",
    jacketAria: "Your jacket",
    insideCap: "Inside: lining and your label",
    cCloth: "Cloth",
    cLapel: "Lapel",
    cFront: "Front",
    cPockets: "Pockets",
    cLining: "Lining",
    cMono: "Monogram",
    monoAria: "Monogram initials",
    monoNote: "Up to three letters, sewn inside.",
    "lapel.notch": "Notch",
    "lapel.peak": "Peak",
    "lapel.shawl": "Shawl",
    "front.sb1": "One button",
    "front.sb2": "Two buttons",
    "front.db": "Double-breasted",
    "pockets.flap": "Flap",
    "pockets.jetted": "Jetted",
    "pockets.patch": "Patch",
    "lining.bordeaux": "Bordeaux",
    "lining.ochre": "Ochre",
    "lining.teal": "Teal",
    "lining.paisley": "Silk paisley",
    eur: "€{n}",
    plus: "+€{n}",
    meta: "{weeks} weeks · {fittings} fittings · {hours} hours of hand work",
    saveDesign: "Keep this design",
    surprise: "Surprise me",
    savedDesign: "Kept. It will come with you when you book a fitting.",
    processKicker: "Process",
    processTitle: "Nine weeks, five visits to the table",
    stepsAria: "Steps",
    week: "Week {n}",
    clothKicker: "Cloth",
    clothTitle: "The bunch book",
    seasonAria: "Season",
    "season.all": "All",
    "season.year": "All year",
    "season.summer": "Summer",
    "season.winter": "Winter",
    useCloth: "Use this cloth",
    inUse: "In your jacket",
    weight: "{g} g/m",
    galleryAria: "From the workroom",
    g1: "Two tweed jackets on tailor's dummies",
    g2: "A dark suit with a silver tie on a stand",
    g3: "A bottle-green suit, buttoned",
    g4: "A navy checked jacket and tie",
    fitKicker: "Fittings",
    fitTitle: "Come and stand on the box",
    fitText: "Tuesday to Saturday. A first visit takes an hour: we measure, talk, and you leave with your cloth chosen.",
    carryTitle: "Bringing your design",
    carryNone: "No design kept yet — <a href=\"#design\">draw one</a> or just come and talk.",
    visitType: "Visit",
    "visit.consult": "First visit",
    "visit.fitting": "Fitting",
    "visit.collect": "Collection",
    visitMin: "{n} min",
    day: "Day",
    time: "Time",
    noSlots: "Fully booked that day — try another.",
    fName: "Name",
    fPhone: "Phone",
    fEmail: "Email",
    confirm: "Confirm the visit",
    errSlot: "Pick a time.",
    errName: "Please add your name.",
    errPhone: "Please add a phone number.",
    errEmail: "That email doesn't look right.",
    booked: "See you on {when}. Your reference is {code}.",
    mineTitle: "Your visits",
    cancel: "Cancel",
    footerLine: "A fictional tailor. Cloth names, prices and the house are made up.",
    moreDemos: "More demos",
    d0: "Sun", d1: "Mon", d2: "Tue", d3: "Wed", d4: "Thu", d5: "Fri", d6: "Sat",
    m0: "Jan", m1: "Feb", m2: "Mar", m3: "Apr", m4: "May", m5: "Jun", m6: "Jul", m7: "Aug", m8: "Sep", m9: "Oct", m10: "Nov", m11: "Dec"
  },
  pt: {
    "title.home": "Atelier Moura — alfaiataria por medida em Lisboa",
    "desc.home": "Alfaiate fictício na Rua dos Fanqueiros. Desenhe o seu casaco em tempo real, escolha o tecido e marque uma prova.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    logoSub: "Alfaiates · Lisboa",
    navDesign: "Desenhar",
    navProcess: "Processo",
    navCloth: "Tecidos",
    navFitting: "Provas",
    bookCta: "Marcar prova",
    kicker: "Rua dos Fanqueiros · desde 1987",
    heroTitle: "Cortado para uma pessoa. <em>Cosido à mão.</em>",
    heroLede: "Um molde em papel desenhado a partir das suas medidas, um casaco alinhavado e provado em si duas vezes, e cerca de sessenta horas de trabalho à mão. Comece por desenhá-lo aqui em baixo.",
    heroCta: "Desenhar o casaco",
    heroHow: "Como é feito",
    f1: "Pontos à mão",
    f2: "Provas",
    f3: "Semanas",
    heroAlt: "Mãos a alisar um casaco de lã cinzenta na mesa de corte",
    heroCap: "Mesa de corte, segundo andar",
    designKicker: "O desenho",
    designTitle: "Desenhe o seu casaco",
    designLede: "Cada escolha redesenha o casaco e o preço. Nada aqui é um modelo feito: é o que marcaríamos a giz no tecido.",
    jacketAria: "O seu casaco",
    insideCap: "Por dentro: forro e a sua etiqueta",
    cCloth: "Tecido",
    cLapel: "Lapela",
    cFront: "Frente",
    cPockets: "Bolsos",
    cLining: "Forro",
    cMono: "Monograma",
    monoAria: "Iniciais do monograma",
    monoNote: "Até três letras, bordadas por dentro.",
    "lapel.notch": "Clássica",
    "lapel.peak": "Em bico",
    "lapel.shawl": "Xaile",
    "front.sb1": "Um botão",
    "front.sb2": "Dois botões",
    "front.db": "Trespassado",
    "pockets.flap": "Com pala",
    "pockets.jetted": "Debruados",
    "pockets.patch": "Chapa",
    "lining.bordeaux": "Bordéus",
    "lining.ochre": "Ocre",
    "lining.teal": "Petróleo",
    "lining.paisley": "Seda cachemira",
    eur: "{n} €",
    plus: "+{n} €",
    meta: "{weeks} semanas · {fittings} provas · {hours} horas de trabalho à mão",
    saveDesign: "Guardar este desenho",
    surprise: "Surpreenda-me",
    savedDesign: "Guardado. Vem consigo quando marcar uma prova.",
    processKicker: "Processo",
    processTitle: "Nove semanas, cinco passagens pela mesa",
    stepsAria: "Etapas",
    week: "Semana {n}",
    clothKicker: "Tecidos",
    clothTitle: "O mostruário",
    seasonAria: "Estação",
    "season.all": "Todos",
    "season.year": "Todo o ano",
    "season.summer": "Verão",
    "season.winter": "Inverno",
    useCloth: "Usar este tecido",
    inUse: "No seu casaco",
    weight: "{g} g/m",
    galleryAria: "Da oficina",
    g1: "Dois casacos de tweed em manequins de alfaiate",
    g2: "Um fato escuro com gravata prateada num suporte",
    g3: "Um fato verde-garrafa, abotoado",
    g4: "Um casaco azul-marinho aos quadrados e gravata",
    fitKicker: "Provas",
    fitTitle: "Venha subir ao estrado",
    fitText: "De terça a sábado. A primeira visita demora uma hora: medimos, conversamos e sai com o tecido escolhido.",
    carryTitle: "Traz o seu desenho",
    carryNone: "Ainda não guardou um desenho — <a href=\"#design\">desenhe um</a> ou venha só conversar.",
    visitType: "Visita",
    "visit.consult": "Primeira visita",
    "visit.fitting": "Prova",
    "visit.collect": "Levantamento",
    visitMin: "{n} min",
    day: "Dia",
    time: "Hora",
    noSlots: "Esse dia está cheio — experimente outro.",
    fName: "Nome",
    fPhone: "Telemóvel",
    fEmail: "Email",
    confirm: "Confirmar a visita",
    errSlot: "Escolha uma hora.",
    errName: "Indique o seu nome.",
    errPhone: "Indique um número de telemóvel.",
    errEmail: "Esse email não parece correto.",
    booked: "Até {when}. A sua referência é {code}.",
    mineTitle: "As suas visitas",
    cancel: "Cancelar",
    footerLine: "Um alfaiate fictício. Os nomes dos tecidos, os preços e a casa são inventados.",
    moreDemos: "Mais demos",
    d0: "Dom", d1: "Seg", d2: "Ter", d3: "Qua", d4: "Qui", d5: "Sex", d6: "Sáb",
    m0: "jan", m1: "fev", m2: "mar", m3: "abr", m4: "mai", m5: "jun", m6: "jul", m7: "ago", m8: "set", m9: "out", m10: "nov", m11: "dez"
  }
};

I18N.start(window.SITE_I18N);
