window.SITE_I18N = {
  en: {
    "title.home": "Atelier — sites with a pulse",
    "title.work": "Work — Atelier",
    "title.offer": "Offer — Atelier",
    "title.contact": "Contact — Atelier",
    "desc.home": "A small studio making expressive websites for shops, salons, kitchens and local trades. Cheap in bulk. Handmade on purpose.",
    "desc.work": "Live demo sites: photographer, restaurant, perfume, salon, bakery, cleaning, and a backoffice.",
    "desc.offer": "Three website packages: lookbook SPA, local complete site, and site plus admin desk.",
    "desc.contact": "Start a batch of websites. Tell us the shop type and how many.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    navHome: "Home",
    navWork: "Work",
    navOffer: "Offer",
    navContact: "Contact",
    eyebrow: "Studio · 2026",
    hero: "<span>Sites that</span><span class=\"italic\">feel</span><span>handmade.</span>",
    lede: "Expressive websites for cafés, salons, kitchens and local trades. Built fast. Priced for bulk. Never a template with the logo swapped.",
    seeDemos: "See the demos",
    packages: "Packages",
    scroll: "Scroll",
    strip: "Kinetic type · Broken grids · Booking desks · Local SEO bones · Mobile first",
    live: "Live demos",
    rooms: "Seven rooms. Seven voices.",
    roomsLede: "Each site lives in its own folder. Open one, sit with it, then tell us which mood you want.",
    lumen: "Photographer lookbook. Cinema scroll, almost no copy.",
    osteria: "A restaurant told as a meal. Editorial, warm, hungry.",
    vela: "Perfume as colour and type. A brand, not a catalogue.",
    aura: "Salon with prices, team, gallery and booking.",
    nido: "Bakery that smiles. Menu, hours, weekend lists.",
    brightline: "Home cleaning that converts. Call, quote, trust.",
    desk: "The salon’s admin. Change a price, watch the site move.",
    sell: "How we sell this",
    three: "Three products. Not “a website”.",
    spa: "Lookbook SPA",
    spaLede: "Lumen, Osteria, Vela. Pride pieces. From €450.",
    local: "Local complete",
    localLede: "Aura, Nido, Brightline. The bulk SKU. From €750.",
    plus: "Site + desk",
    plusLede: "Aura with Aura Desk. You run the shop. From €1,100.",
    footer: "Atelier · fictional studio, real craft.",
    start: "Start a batch",
    demo: "Demo notice",
    demoLink: "I build sites like this",
    workEyebrow: "The rooms",
    workHero: "Open a site. Stay a minute.",
    workLede: "These are not screenshots. They are live, isolated folders you can host on GitHub Pages as-is.",
    lumenLong: "Photographer SPA · dark cinema · kinetic name · work as a film strip.",
    osteriaLong: "Restaurant SPA · paper and wine · dishes as chapters · reservation card.",
    velaLong: "Perfume SPA · broken grid · saturated colour · product as art.",
    auraLong: "Salon · services, team, gallery, booking · the volume SKU.",
    nidoLong: "Bakery · loud butter yellow · menu, hours, events, catering.",
    brightLong: "Cleaning · click-to-call · service pages · quote form · trust.",
    deskLong: "Backoffice · demo / demo · edit Aura’s prices and bookings.",
    offerEyebrow: "Packages",
    offerHero: "Cheap in bulk. Not cheap looking.",
    offerLede: "Pick the nearest demo. We restyle it, swap the words, and ship. Prices are starting points for a batch of similar shops.",
    lookbook: "Lookbook",
    most: "Most booked",
    upsell: "Upsell",
    spaBody: "One long page with a signature move: scroll, type, colour. For photographers, kitchens, small brands.",
    spa1: "Single-page experience",
    spa2: "Contact or reservation card",
    spa3: "Mobile-first, fast",
    spa4: "Hosted on GitHub Pages",
    spaRef: "See Lumen, Osteria, Vela.",
    localTitle: "Local complete",
    localBody: "Real pages a shop needs: services, prices, hours, gallery, form, click-to-call.",
    local1: "5–8 pages",
    local2: "WhatsApp / phone on every screen",
    local3: "FAQ and map",
    local4: "Ready for Google Business",
    localRef: "See Aura, Nido, Brightline.",
    deskTitle: "Site + desk",
    deskBody: "The public site plus a small backoffice. Change a price. Mark a booking done.",
    desk1: "Everything in Local complete",
    desk2: "Admin login",
    desk3: "Services, hours, bookings",
    desk4: "Site reads the same data",
    deskRef: "See Aura + Aura Desk.",
    process: "Process",
    processTitle: "A batch, not a mystery.",
    step1: "Pick a sibling",
    step1b: "You point at a demo. That is the skeleton.",
    step2: "Words and photos",
    step2b: "You send a menu, a price list, a phone number.",
    step3: "Restyle and ship",
    step3b: "New type, new colour, same bones. Live in days.",
    contactEyebrow: "Contact",
    contactHero: "Tell us the batch.",
    contactLede: "This form is a demo. On a live job it can land in your inbox. For now it confirms on the page.",
    name: "Name",
    email: "Email",
    kind: "What are we making?",
    kindSpa: "Lookbook SPA",
    kindLocal: "Local complete",
    kindDesk: "Site + desk",
    kindBatch: "A batch of shops",
    count: "How many sites?",
    notes: "Notes",
    notesPh: "City, trade, language, a demo you liked.",
    send: "Send the note",
    formNeed: "Add a name so we know who to answer.",
    formOk: "Noted, {name}. This demo does not send email yet."
  },
  pt: {
    "title.home": "Atelier — sites com pulso",
    "title.work": "Trabalho — Atelier",
    "title.offer": "Oferta — Atelier",
    "title.contact": "Contacto — Atelier",
    "desc.home": "Um estúdio pequeno a fazer sites expressivos para lojas, cabeleireiros, cozinhas e ofícios locais. Baratos em série. Feitos à mão de propósito.",
    "desc.work": "Demos ao vivo: fotógrafo, restaurante, perfume, cabeleireiro, padaria, limpezas e um backoffice.",
    "desc.offer": "Três pacotes: SPA lookbook, site local completo e site com secretária.",
    "desc.contact": "Comece um lote de sites. Diga-nos o tipo de loja e quantos.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    navHome: "Início",
    navWork: "Trabalho",
    navOffer: "Oferta",
    navContact: "Contacto",
    eyebrow: "Estúdio · 2026",
    hero: "<span>Sites que</span><span class=\"italic\">se sentem</span><span>feitos à mão.</span>",
    lede: "Sites expressivos para cafés, cabeleireiros, cozinhas e ofícios locais. Rápidos de fazer. Preço para série. Nunca um modelo com o logótipo trocado.",
    seeDemos: "Ver as demos",
    packages: "Pacotes",
    scroll: "Deslizar",
    strip: "Tipo cinético · Grelhas partidas · Secretárias de marcações · Base de SEO local · Telemóvel primeiro",
    live: "Demos ao vivo",
    rooms: "Sete salas. Sete vozes.",
    roomsLede: "Cada site vive na sua pasta. Abra um, fique um minuto, diga-nos o tom que quer.",
    lumen: "Portefólio de fotógrafo. Scroll de cinema, quase sem texto.",
    osteria: "Um restaurante contado como uma refeição. Editorial, quente, com fome.",
    vela: "Perfume como cor e letra. Uma marca, não um catálogo.",
    aura: "Cabeleireiro com preços, equipa, galeria e marcações.",
    nido: "Padaria que sorri. Ementa, horário, fins-de-semana.",
    brightline: "Limpezas que convertem. Ligar, orçamento, confiança.",
    desk: "A secretária do salão. Mude um preço, veja o site mexer.",
    sell: "Como vendemos isto",
    three: "Três produtos. Não “um site”.",
    spa: "SPA lookbook",
    spaLede: "Lumen, Osteria, Vela. Peças de orgulho. Desde €450.",
    local: "Local completo",
    localLede: "Aura, Nido, Brightline. O produto de série. Desde €750.",
    plus: "Site + secretária",
    plusLede: "Aura com Aura Desk. A loja fica consigo. Desde €1.100.",
    footer: "Atelier · estúdio de ficção, ofício a sério.",
    start: "Começar um lote",
    demo: "Aviso de demo",
    demoLink: "Faço sites assim",
    workEyebrow: "As salas",
    workHero: "Abra um site. Fique um minuto.",
    workLede: "Não são capturas. São pastas isoladas, prontas para o GitHub Pages.",
    lumenLong: "SPA de fotógrafo · cinema escuro · nome cinético · trabalho em tira de filme.",
    osteriaLong: "SPA de restaurante · papel e vinho · pratos em capítulos · cartão de reserva.",
    velaLong: "SPA de perfume · grelha partida · cor saturada · produto como arte.",
    auraLong: "Cabeleireiro · serviços, equipa, galeria, marcações · o produto de volume.",
    nidoLong: "Padaria · amarelo-manteiga · ementa, horário, eventos, catering.",
    brightLong: "Limpezas · clique para ligar · páginas de serviço · orçamento · confiança.",
    deskLong: "Backoffice · demo / demo · edite preços e marcações da Aura.",
    offerEyebrow: "Pacotes",
    offerHero: "Barato em série. Sem cara barata.",
    offerLede: "Escolha a demo mais próxima. Mudamos o visual, as palavras, e publicamos. Os preços são ponto de partida para um lote de lojas parecidas.",
    lookbook: "Lookbook",
    most: "O mais pedido",
    upsell: "Extra",
    spaBody: "Uma página longa com um gesto próprio: scroll, letra, cor. Para fotógrafos, cozinhas, marcas pequenas.",
    spa1: "Experiência numa só página",
    spa2: "Cartão de contacto ou reserva",
    spa3: "Telemóvel primeiro, rápido",
    spa4: "Alojado no GitHub Pages",
    spaRef: "Ver Lumen, Osteria, Vela.",
    localTitle: "Local completo",
    localBody: "As páginas que uma loja precisa: serviços, preços, horário, galeria, formulário, clique para ligar.",
    local1: "5–8 páginas",
    local2: "WhatsApp / telefone em todos os ecrãs",
    local3: "Perguntas frequentes e mapa",
    local4: "Pronto para o Perfil de Empresa Google",
    localRef: "Ver Aura, Nido, Brightline.",
    deskTitle: "Site + secretária",
    deskBody: "O site público e um backoffice pequeno. Mude um preço. Marque uma reserva como feita.",
    desk1: "Tudo do Local completo",
    desk2: "Entrada de administração",
    desk3: "Serviços, horário, marcações",
    desk4: "O site lê os mesmos dados",
    deskRef: "Ver Aura + Aura Desk.",
    process: "Processo",
    processTitle: "Um lote, sem mistério.",
    step1: "Escolher um irmão",
    step1b: "Aponta para uma demo. Isso é o esqueleto.",
    step2: "Palavras e fotos",
    step2b: "Envia uma ementa, uma lista de preços, um telefone.",
    step3: "Revestir e publicar",
    step3b: "Letra nova, cor nova, os mesmos ossos. No ar em dias.",
    contactEyebrow: "Contacto",
    contactHero: "Diga-nos o lote.",
    contactLede: "Este formulário é uma demo. Num trabalho a sério pode ir para o seu e-mail. Por agora confirma na página.",
    name: "Nome",
    email: "E-mail",
    kind: "O que vamos fazer?",
    kindSpa: "SPA lookbook",
    kindLocal: "Local completo",
    kindDesk: "Site + secretária",
    kindBatch: "Um lote de lojas",
    count: "Quantos sites?",
    notes: "Notas",
    notesPh: "Cidade, ofício, idioma, uma demo de que gostou.",
    send: "Enviar a nota",
    formNeed: "Ponha um nome para sabermos a quem responder.",
    formOk: "Ficou, {name}. Esta demo ainda não envia e-mail."
  }
};

I18N.start(window.SITE_I18N);
