window.SITE_I18N = {
  en: {
    "title.home": "Vela N°07 — Night Bloom",
    "desc.home": "Fictional perfume house. One fragrance, Night Bloom: tuberose, ink and the heat that stays in a room.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    navNotes: "Notes",
    navWear: "On skin",
    navMaking: "Making",
    navFormats: "Formats",
    kicker: "N°07 · Night Bloom · Eau de parfum",
    heroTitle: "Wear the hour after the lights go out.",
    heroLede: "One fragrance, made in small batches in Lisboa. Tuberose that isn't polite, ink, and the warmth a room keeps after everyone has left.",
    heroCta: "Request a sample",
    bottleAria: "The Night Bloom bottle",
    notesKicker: "The notes",
    notesTitle: "Three layers, one evening",
    "l.top": "Top",
    "l.heart": "Heart",
    "l.base": "Base",
    "ld.top": "The first ten minutes. Bright, a little sharp, gone before you notice.",
    "ld.heart": "The evening itself. Heady florals that open in the warmth of skin.",
    "ld.base": "What stays on a scarf the next morning.",
    "n.orange": "Bitter orange peel",
    "n.pepper": "Pink pepper",
    "n.match": "A struck match",
    "n.tuberose": "Tuberose absolute",
    "n.jasmine": "Night jasmine",
    "n.plum": "Dark plum",
    "n.ink": "Ink accord",
    "n.suede": "Suede",
    "n.smoke": "Cedar smoke",
    "n.amber": "Warm amber",
    intensity: "Intensity",
    wearKicker: "On skin",
    wearTitle: "The wear clock",
    wearText: "Drag through the night and see what is still there.",
    wearSlider: "Hours after spraying",
    hoursAfter: "{h} h after spraying",
    justSprayed: "Just sprayed",
    "m.0": "— bright and loud",
    "m.1": "— the flowers open",
    "m.4": "— close to the skin",
    "m.8": "— a trace on fabric",
    makingKicker: "Making",
    makingTitle: "Two hundred bottles at a time",
    makingText: "Each batch macerates for eight weeks before it is filled by hand and numbered. When a batch is gone, we wait for the next one.",
    alt1: "Orange flowers against a blue sky",
    alt2: "A hand holding a glass dropper",
    alt3: "Glass bottles on a table in soft focus",
    cap1: "Flowers, picked at dawn",
    cap2: "Blended drop by drop",
    cap3: "Batch 14, resting",
    formatsKicker: "Formats",
    formatsTitle: "Try it first",
    "f.sample": "Sample",
    "f.travel": "Travel",
    "f.full": "Bottle",
    "fd.sample": "2 ml vial in a paper sleeve. Free, you pay postage.",
    "fd.travel": "10 ml refillable atomiser for a bag or a pocket.",
    "fd.full": "50 ml, numbered by hand. Batch 14.",
    free: "Free",
    postage: "+ 4 € postage",
    left: "{n} left in this batch",
    fName: "Name",
    fEmail: "Email",
    fCity: "City",
    send: "Send request",
    totalLine: "{name}: {price}",
    errName: "Please add your name.",
    errEmail: "Please add an email so we can confirm.",
    sent: "Thank you, {name}. Your {format} is on our list — we post every Tuesday. (Demo: nothing was sent.)",
    footerLine: "A fictional perfume house. The bottle is drawn, not photographed.",
    backAtelier: "More demos"
  },
  pt: {
    "title.home": "Vela N°07 — Night Bloom",
    "desc.home": "Casa de perfumes fictícia. Uma fragrância, Night Bloom: nardo, tinta e o calor que fica numa sala.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    navNotes: "Notas",
    navWear: "Na pele",
    navMaking: "Feitura",
    navFormats: "Formatos",
    kicker: "N°07 · Night Bloom · Eau de parfum",
    heroTitle: "Use a hora depois de as luzes se apagarem.",
    heroLede: "Uma fragrância, feita em pequenos lotes em Lisboa. Nardo sem boas maneiras, tinta e o calor que uma sala guarda depois de todos saírem.",
    heroCta: "Pedir uma amostra",
    bottleAria: "O frasco Night Bloom",
    notesKicker: "As notas",
    notesTitle: "Três camadas, uma noite",
    "l.top": "Topo",
    "l.heart": "Coração",
    "l.base": "Fundo",
    "ld.top": "Os primeiros dez minutos. Luminosas, um pouco ácidas, desaparecem antes de dar por elas.",
    "ld.heart": "A noite propriamente dita. Florais intensos que abrem com o calor da pele.",
    "ld.base": "O que fica num lenço na manhã seguinte.",
    "n.orange": "Casca de laranja amarga",
    "n.pepper": "Pimenta rosa",
    "n.match": "Um fósforo aceso",
    "n.tuberose": "Absoluto de nardo",
    "n.jasmine": "Jasmim da noite",
    "n.plum": "Ameixa escura",
    "n.ink": "Acorde de tinta",
    "n.suede": "Camurça",
    "n.smoke": "Fumo de cedro",
    "n.amber": "Âmbar quente",
    intensity: "Intensidade",
    wearKicker: "Na pele",
    wearTitle: "O relógio na pele",
    wearText: "Arraste pela noite fora e veja o que ainda lá está.",
    wearSlider: "Horas depois de aplicar",
    hoursAfter: "{h} h depois de aplicar",
    justSprayed: "Acabado de aplicar",
    "m.0": "— luminoso e intenso",
    "m.1": "— as flores abrem",
    "m.4": "— junto à pele",
    "m.8": "— um rasto no tecido",
    makingKicker: "Feitura",
    makingTitle: "Duzentos frascos de cada vez",
    makingText: "Cada lote macera durante oito semanas antes de ser cheio à mão e numerado. Quando um lote acaba, esperamos pelo seguinte.",
    alt1: "Flores laranja contra um céu azul",
    alt2: "Uma mão a segurar um conta-gotas de vidro",
    alt3: "Frascos de vidro numa mesa, desfocados",
    cap1: "Flores, colhidas de madrugada",
    cap2: "Misturado gota a gota",
    cap3: "Lote 14, a repousar",
    formatsKicker: "Formatos",
    formatsTitle: "Experimente primeiro",
    "f.sample": "Amostra",
    "f.travel": "Viagem",
    "f.full": "Frasco",
    "fd.sample": "Frasco de 2 ml numa capa de papel. Grátis, paga os portes.",
    "fd.travel": "Vaporizador recarregável de 10 ml para a mala ou o bolso.",
    "fd.full": "50 ml, numerado à mão. Lote 14.",
    free: "Grátis",
    postage: "+ 4 € de portes",
    left: "Restam {n} neste lote",
    fName: "Nome",
    fEmail: "Email",
    fCity: "Cidade",
    send: "Enviar pedido",
    totalLine: "{name}: {price}",
    errName: "Indique o seu nome.",
    errEmail: "Indique um email para confirmarmos.",
    sent: "Obrigado, {name}. O seu pedido de {format} está na lista — enviamos todas as terças-feiras. (Demo: nada foi enviado.)",
    footerLine: "Uma casa de perfumes fictícia. O frasco é desenhado, não fotografado.",
    backAtelier: "Mais demos"
  }
};

I18N.start(window.SITE_I18N);
