window.SITE_I18N = {
  en: {
    title: "Vela — a perfume, not a catalogue",
    desc: "Fictional perfume house. Saturated colour, broken grid, notes you can open.",
    skip: "Skip to notes",
    lang: "Language",
    notes: "Notes",
    look: "Look",
    ask: "Ask",
    kicker: "N°07 · Night Bloom",
    hero: "Wear the hour after the lights go out.",
    lead: "A fictional house. One juice. No seasonal drop. Tuberose, ink, and the heat that stays in a room.",
    top: "Top",
    topCopy: "Bitter orange peel, pink pepper, a struck match.",
    heart: "Heart",
    heartCopy: "Tuberose, not polite. Jasmine that refuses daylight.",
    base: "Base",
    baseCopy: "Ink, suede, a little smoke. Skin remembers it.",
    lookTitle: "Not a shop. A look.",
    cap1: "House still · 01",
    cap2: "House still · 02",
    cap3: "Cloth · evening",
    price: "Night Bloom · 50 ml · <s>€190</s> sample on request",
    askTitle: "Ask for a sample.",
    name: "Name",
    email: "Email",
    city: "City",
    request: "Request",
    formOk: "Sample noted. A live house would post a vial.",
    demo: "Demo notice",
    demoLink: "I build sites like this"
  },
  pt: {
    title: "Vela — um perfume, não um catálogo",
    desc: "Casa de perfume de ficção. Cor saturada, grelha partida, notas que se abrem.",
    skip: "Saltar para as notas",
    lang: "Idioma",
    notes: "Notas",
    look: "Olhar",
    ask: "Pedir",
    kicker: "N°07 · Night Bloom",
    hero: "Vista a hora depois de se apagarem as luzes.",
    lead: "Uma casa de ficção. Um suco. Sem lançamento de estação. Túbera, tinta e o calor que fica no quarto.",
    top: "Saída",
    topCopy: "Casca de laranja amarga, pimenta-rosa, um fósforo riscado.",
    heart: "Coração",
    heartCopy: "Túbera, sem educação. Jasmim que recusa a luz do dia.",
    base: "Fundo",
    baseCopy: "Tinta, camurça, um pouco de fumo. A pele lembra-se.",
    lookTitle: "Não é uma loja. É um olhar.",
    cap1: "Still da casa · 01",
    cap2: "Still da casa · 02",
    cap3: "Pano · noite",
    price: "Night Bloom · 50 ml · <s>€190</s> amostra a pedido",
    askTitle: "Peça uma amostra.",
    name: "Nome",
    email: "E-mail",
    city: "Cidade",
    request: "Pedir",
    formOk: "Amostra anotada. Uma casa a sério enviaria um frasco.",
    demo: "Aviso de demo",
    demoLink: "Faço sites assim"
  }
};

I18N.start(window.SITE_I18N);
