window.SITE_I18N = {
  en: {
    title: "Osteria Corvo — one sitting",
    desc: "Fictional neighbourhood restaurant. A meal told as chapters. Reservations on the last card.",
    skip: "Skip to the meal",
    lang: "Language",
    menu: "Menu",
    cellar: "Cellar",
    table: "Table",
    season: "Autumn sitting · Lisboa",
    hero: "<span>Come</span><span>hungry.</span><span class=\"soft\">Leave later.</span>",
    openCopy: "A fictional room of twelve tables. Fire, paper menus, and a kitchen that cooks one sitting at a time.",
    ask: "Ask for a table",
    begin: "To begin",
    olives: "Warm olives, orange wood",
    olivesCopy: "Castelvetrano, a strip of peel, oil that has seen the fire. Bread from the morning, still arguing with the crust.",
    pasta: "The pasta",
    tonnarelli: "Tonnarelli cacio e pepe",
    pastaCopy: "Pepper cracked at the table. Cheese from a wheel we finish in a week. No cream. No apology.",
    bird: "The bird",
    fowl: "Guinea fowl, grapes, bay",
    birdCopy: "Roasted until the skin sounds right. A pan sauce of last week's wine and this week's fruit.",
    glass: "The glass",
    pour: "We pour what we drink.",
    wine1: "salt, almond, a cold night",
    wine2: "cherry, dust, the long story",
    wine3: "with the cheese, if you stay",
    aTable: "A table",
    night: "Write the night you want.",
    name: "Name",
    guests: "Guests",
    date: "Date",
    note: "Note",
    notePh: "Window, late, no shellfish.",
    hold: "Hold the table",
    fine: "Tue–Sat · 19:00 sitting · Rua do Demo 12",
    formOk: "Held on paper, {name}. A live restaurant would confirm by phone.",
    demo: "Demo notice",
    demoLink: "I build sites like this"
  },
  pt: {
    title: "Osteria Corvo — um serviço",
    desc: "Restaurante de bairro de ficção. Uma refeição em capítulos. Reservas no último cartão.",
    skip: "Saltar para a refeição",
    lang: "Idioma",
    menu: "Ementa",
    cellar: "Adega",
    table: "Mesa",
    season: "Serviço de outono · Lisboa",
    hero: "<span>Venha</span><span>com fome.</span><span class=\"soft\">Saia mais tarde.</span>",
    openCopy: "Uma sala de ficção com doze mesas. Fogo, ementas de papel e uma cozinha que cozinha um serviço de cada vez.",
    ask: "Pedir uma mesa",
    begin: "Para começar",
    olives: "Azeitonas quentes, madeira de laranjeira",
    olivesCopy: "Castelvetrano, uma tira de casca, azeite que já viu o fogo. Pão da manhã, ainda a discutir com a côdea.",
    pasta: "A massa",
    tonnarelli: "Tonnarelli cacio e pepe",
    pastaCopy: "Pimenta partida à mesa. Queijo de uma roda que acaba numa semana. Sem natas. Sem desculpa.",
    bird: "A ave",
    fowl: "Pintada, uvas, louro",
    birdCopy: "Assada até a pele soar bem. Um molho da frigideira com o vinho da semana passada e a fruta desta.",
    glass: "O copo",
    pour: "Deitamos o que bebemos.",
    wine1: "sal, amêndoa, uma noite fria",
    wine2: "cereja, pó, a história longa",
    wine3: "com o queijo, se ficar",
    aTable: "Uma mesa",
    night: "Escreva a noite que quer.",
    name: "Nome",
    guests: "Pessoas",
    date: "Data",
    note: "Nota",
    notePh: "Janela, tarde, sem marisco.",
    hold: "Segurar a mesa",
    fine: "Ter–Sáb · serviço às 19:00 · Rua do Demo 12",
    formOk: "Ficou no papel, {name}. Um restaurante a sério confirmaria por telefone.",
    demo: "Aviso de demo",
    demoLink: "Faço sites assim"
  }
};

I18N.start(window.SITE_I18N);
