window.SITE_I18N = {
  en: {
    "title.home": "Osteria Corvo — one menu, two sittings",
    "desc.home": "Fictional restaurant in Lisboa. Five courses, two sittings a night, a short cellar and live table booking.",
    skip: "Skip to content",
    lang: "Language",
    menuBtn: "Menu",
    navTonight: "Tonight",
    navCellar: "Cellar",
    navVisit: "Visit",
    reserve: "Reserve",
    kicker: "Príncipe Real · Lisboa · twelve tables",
    heroTitle: "One menu.<br><i>Two sittings.</i><br>No hurry.",
    heroLede: "Five courses cooked for the whole room at once, at seven and at half past nine. You choose the night; we choose the food.",
    heroAlt: "The dining room with plants and warm lamps",
    heroCap: "The room, ten minutes before the first sitting.",
    liveSeats: "{day}: {seats} seats left at {time}",
    liveFull: "Tonight is full — next table {day} at {time}",
    tonightKicker: "This week's menu",
    tonightTitle: "Tonight, in five chapters",
    pairing: "Wine pairing",
    priceMenu: "Menu {menu} € per person",
    priceBoth: "Menu {menu} € + pairing {pair} € = {total} €",
    glass: "Glass",
    kitchenKicker: "The kitchen",
    kitchenTitle: "Market at nine, menu by noon",
    kitchenText: "Chef Leonor Abreu writes the week's menu after the Thursday market and keeps it until it runs out. Tell us about allergies when you book and the plate changes with you.",
    kitchenAlt: "A cook chopping herbs on a board",
    cellarKicker: "The cellar",
    cellarTitle: "Small growers, honest prices",
    filterAria: "Filter wines",
    all: "All",
    "w.red": "Red",
    "w.white": "White",
    "w.orange": "Orange",
    "w.sparkling": "Sparkling",
    perGlass: "glass",
    perBottle: "bottle",
    cellarNote: "Corkage on your own bottle: 15 €. Ask us for the reserve list.",
    reserveKicker: "Reservations",
    reserveTitle: "Ask for a table",
    reserveText: "Tables hold for fifteen minutes. For more than eight people, call us and we'll close the room for you.",
    guests: "Guests",
    fewer: "Fewer guests",
    more: "More guests",
    night: "Night",
    sitting: "Sitting",
    seatsLeft: "{n} seats left",
    full: "Full",
    closedShort: "Closed",
    today: "Tonight",
    fName: "Name",
    fPhone: "Phone",
    dietTitle: "Anything we should cook around?",
    "diet.veg": "Vegetarian",
    "diet.gluten": "No gluten",
    "diet.shellfish": "No shellfish",
    "diet.nuts": "Nut allergy",
    "diet.dairy": "No dairy",
    "diet.celebrate": "We're celebrating",
    submit: "Reserve for {n} · {day} at {time}",
    submitPick: "Pick a night and a sitting",
    errName: "Please add a name for the table.",
    errPhone: "Please add a phone number.",
    errSeats: "Not enough seats left in that sitting — try the other one.",
    mineTitle: "Your reservations",
    mineLine: "{ref} · {n} guests · {day} at {time}",
    cancel: "Cancel",
    confirmed: "Table held — reference {ref}. (Demo: kept in this browser.)",
    cancelled: "Reservation {ref} cancelled.",
    visitKicker: "Visit",
    tueSat: "Tuesday – Saturday",
    sunMon: "Sunday, Monday",
    closed: "Closed",
    kitchenCloses: "Kitchen closes",
    footerLine: "A fictional restaurant. Photographs from Unsplash.",
    backAtelier: "More demos",
    d0: "Sun", d1: "Mon", d2: "Tue", d3: "Wed", d4: "Thu", d5: "Fri", d6: "Sat",
    months: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec"
  },
  pt: {
    "title.home": "Osteria Corvo — um menu, dois turnos",
    "desc.home": "Restaurante fictício em Lisboa. Cinco pratos, dois turnos por noite, uma garrafeira curta e reservas em tempo real.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menuBtn: "Menu",
    navTonight: "Hoje",
    navCellar: "Garrafeira",
    navVisit: "Visitar",
    reserve: "Reservar",
    kicker: "Príncipe Real · Lisboa · doze mesas",
    heroTitle: "Um menu.<br><i>Dois turnos.</i><br>Sem pressa.",
    heroLede: "Cinco pratos cozinhados para a sala inteira ao mesmo tempo, às sete e às nove e meia. Escolhe a noite; nós escolhemos a comida.",
    heroAlt: "A sala com plantas e candeeiros quentes",
    heroCap: "A sala, dez minutos antes do primeiro turno.",
    liveSeats: "{day}: {seats} lugares livres às {time}",
    liveFull: "Hoje está cheio — próxima mesa {day} às {time}",
    tonightKicker: "O menu desta semana",
    tonightTitle: "Esta noite, em cinco capítulos",
    pairing: "Harmonização de vinhos",
    priceMenu: "Menu {menu} € por pessoa",
    priceBoth: "Menu {menu} € + harmonização {pair} € = {total} €",
    glass: "Copo",
    kitchenKicker: "A cozinha",
    kitchenTitle: "Mercado às nove, menu ao meio-dia",
    kitchenText: "A chef Leonor Abreu escreve o menu da semana depois do mercado de quinta-feira e mantém-no até acabar. Fale-nos das alergias quando reservar e o prato muda consigo.",
    kitchenAlt: "Um cozinheiro a picar ervas numa tábua",
    cellarKicker: "A garrafeira",
    cellarTitle: "Pequenos produtores, preços honestos",
    filterAria: "Filtrar vinhos",
    all: "Todos",
    "w.red": "Tinto",
    "w.white": "Branco",
    "w.orange": "Curtimenta",
    "w.sparkling": "Espumante",
    perGlass: "copo",
    perBottle: "garrafa",
    cellarNote: "Rolha para garrafa trazida por si: 15 €. Peça-nos a lista de reserva.",
    reserveKicker: "Reservas",
    reserveTitle: "Peça uma mesa",
    reserveText: "As mesas ficam guardadas quinze minutos. Para mais de oito pessoas, ligue-nos e fechamos a sala para si.",
    guests: "Pessoas",
    fewer: "Menos pessoas",
    more: "Mais pessoas",
    night: "Noite",
    sitting: "Turno",
    seatsLeft: "{n} lugares livres",
    full: "Cheio",
    closedShort: "Fechado",
    today: "Hoje",
    fName: "Nome",
    fPhone: "Telemóvel",
    dietTitle: "Há algo a ter em conta na cozinha?",
    "diet.veg": "Vegetariano",
    "diet.gluten": "Sem glúten",
    "diet.shellfish": "Sem marisco",
    "diet.nuts": "Alergia a frutos secos",
    "diet.dairy": "Sem lacticínios",
    "diet.celebrate": "Estamos a celebrar",
    submit: "Reservar para {n} · {day} às {time}",
    submitPick: "Escolha uma noite e um turno",
    errName: "Indique um nome para a mesa.",
    errPhone: "Indique um telemóvel.",
    errSeats: "Não há lugares suficientes nesse turno — experimente o outro.",
    mineTitle: "As suas reservas",
    mineLine: "{ref} · {n} pessoas · {day} às {time}",
    cancel: "Cancelar",
    confirmed: "Mesa guardada — referência {ref}. (Demo: fica guardada neste browser.)",
    cancelled: "Reserva {ref} cancelada.",
    visitKicker: "Visitar",
    tueSat: "Terça – sábado",
    sunMon: "Domingo, segunda",
    closed: "Fechado",
    kitchenCloses: "A cozinha fecha",
    footerLine: "Um restaurante fictício. Fotografias do Unsplash.",
    backAtelier: "Mais demos",
    d0: "Dom", d1: "Seg", d2: "Ter", d3: "Qua", d4: "Qui", d5: "Sex", d6: "Sáb",
    months: "jan,fev,mar,abr,mai,jun,jul,ago,set,out,nov,dez"
  }
};

I18N.start(window.SITE_I18N);
