window.SITE_I18N = {
  en: {
    "title.home": "Brightline — homes left brighter",
    "title.services": "Services — Brightline",
    "title.deep": "Deep clean — Brightline",
    "title.move": "Move-out clean — Brightline",
    "title.office": "Office clean — Brightline",
    "title.areas": "Areas — Brightline",
    "title.quote": "Quote — Brightline",
    "title.contact": "Contact — Brightline",
    desc: "Fictional home cleaning in Lisboa. Click to call, service pages, quotes, trust.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    navHome: "Home",
    navServices: "Services",
    navAreas: "Areas",
    navQuote: "Quote",
    navContact: "Contact",
    top: "Lisboa &amp; nearby · insured team",
    call: "Call +351 21 000 222",
    callNow: "Call now",
    slot: "Home cleaning · same-week slots",
    hero: "A house you can walk into after work.",
    lede: "Fictional crew, real pattern: call, book a room count, we leave the keys where you asked.",
    quote: "Get a quote",
    insured: "Insured",
    insuredC: "Named team. No surprise faces on the day.",
    products: "Products you pick",
    productsC: "Scent-free or citrus. We bring both.",
    week: "Same week",
    weekC: "Most first visits land in three to five days.",
    sendFor: "What people send us for",
    deep: "Deep clean",
    deepC: "The first visit. Baseboards, oven, the room you have been avoiding.",
    move: "Move-out",
    moveC: "Deposit photos. We clean to the inventory, not to a vibe.",
    office: "Office",
    officeC: "After hours. Bins, glass, the kitchen no one claims.",
    pick: "Pick the job.",
    pickLede: "Each service has its own page so a search can land on the right work.",
    deepFrom: "From €95 · first visit, 2–3 hours",
    moveFrom: "From €140 · inventory-led",
    officeFrom: "From €80 · after 18:00",
    deepTitle: "Deep clean.",
    deepLede: "The first visit. Kitchen, bath, floors, the dust that lives behind the sofa. From €95.",
    deep1: "Kitchen including appliance fronts and hob",
    deep2: "Bathrooms descaled",
    deep3: "Floors vacuumed and mopped",
    deep4: "Interior glass",
    quoteJob: "Quote this job",
    moveTitle: "Move-out.",
    moveLede: "Empty rooms, inventory list, photos if the agency wants them. From €140.",
    moveCopy: "Send the checkout notes. We clean to that paper, not to a generic checklist.",
    officeTitle: "Office.",
    officeLede: "After hours. Desks, glass, kitchen, bins. From €80 a visit or a weekly plan.",
    officeCopy: "We do not sit in your Slack. We leave the key with the guard.",
    where: "Where we drive.",
    whereLede: "Fictional coverage for the demo. A live job would list every parish you want to rank for.",
    rooms: "Tell us the rooms.",
    name: "Name",
    phone: "Phone",
    job: "Job",
    parish: "Parish",
    notes: "Notes",
    notesPh: "Pets, keybox, scent-free.",
    sendQ: "Send quote request",
    talk: "Talk to the desk.",
    faq: "Questions owners actually ask",
    q1: "Do we need to be home?",
    a1: "No. A keybox or a neighbour is enough. We send a photo when we lock up.",
    q2: "Are you insured?",
    a2: "In a live job: yes, and the certificate sits on this page. This demo only shows the pattern.",
    q3: "What if a slot slips?",
    a3: "We call before 09:00. You can move the visit once at no charge.",
    hoursBar: "Mon–Sat 08:00–19:00",
    footer: "Brightline · fictional cleaning company",
    formOk: "Quote noted. A live crew would call within the hour.",
    demo: "Demo notice",
    demoLink: "I build sites like this"
  },
  pt: {
    "title.home": "Brightline — casas mais claras",
    "title.services": "Serviços — Brightline",
    "title.deep": "Limpeza profunda — Brightline",
    "title.move": "Limpeza de saída — Brightline",
    "title.office": "Limpeza de escritório — Brightline",
    "title.areas": "Zonas — Brightline",
    "title.quote": "Orçamento — Brightline",
    "title.contact": "Contacto — Brightline",
    desc: "Limpezas de casa de ficção em Lisboa. Clique para ligar, páginas de serviço, orçamentos, confiança.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    navHome: "Início",
    navServices: "Serviços",
    navAreas: "Zonas",
    navQuote: "Orçamento",
    navContact: "Contacto",
    top: "Lisboa e arredores · equipa segurada",
    call: "Ligar +351 21 000 222",
    callNow: "Ligar agora",
    slot: "Limpezas de casa · vagas na mesma semana",
    hero: "Uma casa em que se entra depois do trabalho.",
    lede: "Equipa de ficção, padrão a sério: liga, marca o número de divisões, deixamos as chaves onde pediu.",
    quote: "Pedir orçamento",
    insured: "Segurada",
    insuredC: "Equipa com nome. Sem caras surpresa no dia.",
    products: "Produtos à sua escolha",
    productsC: "Sem cheiro ou cítrico. Levamos os dois.",
    week: "Na mesma semana",
    weekC: "A maior parte das primeiras visitas cai em três a cinco dias.",
    sendFor: "O que as pessoas nos pedem",
    deep: "Limpeza profunda",
    deepC: "A primeira visita. Rodapés, forno, a divisão que tem evitado.",
    move: "Saída de casa",
    moveC: "Fotos do depósito. Limpamos pelo inventário, não por um ambiente.",
    office: "Escritório",
    officeC: "Depois de horas. Caixotes, vidros, a cozinha de que ninguém se reclama.",
    pick: "Escolha o trabalho.",
    pickLede: "Cada serviço tem a sua página para a pesquisa cair no sítio certo.",
    deepFrom: "Desde €95 · primeira visita, 2–3 horas",
    moveFrom: "Desde €140 · guiada pelo inventário",
    officeFrom: "Desde €80 · depois das 18:00",
    deepTitle: "Limpeza profunda.",
    deepLede: "A primeira visita. Cozinha, casa de banho, chão, o pó atrás do sofá. Desde €95.",
    deep1: "Cozinha incluindo frentes de electrodomésticos e placa",
    deep2: "Casas de banho descalcificadas",
    deep3: "Chão aspirado e esfregado",
    deep4: "Vidros interiores",
    quoteJob: "Orçamentar este trabalho",
    moveTitle: "Saída de casa.",
    moveLede: "Divisões vazias, lista de inventário, fotos se a agência as quiser. Desde €140.",
    moveCopy: "Envie as notas de entrega. Limpamos por esse papel, não por uma lista genérica.",
    officeTitle: "Escritório.",
    officeLede: "Depois de horas. Secretárias, vidros, cozinha, caixotes. Desde €80 por visita ou um plano semanal.",
    officeCopy: "Não nos sentamos no seu Slack. Deixamos a chave com o segurança.",
    where: "Onde conduzimos.",
    whereLede: "Cobertura de ficção para a demo. Um trabalho a sério listaria cada freguesia em que quer aparecer.",
    rooms: "Diga-nos as divisões.",
    name: "Nome",
    phone: "Telemóvel",
    hoursBar: "Seg–Sáb 08:00–19:00",
    job: "Trabalho",
    parish: "Freguesia",
    notes: "Notas",
    notesPh: "Animais, caixa de chaves, sem cheiro.",
    sendQ: "Enviar pedido de orçamento",
    talk: "Fale com a secretária.",
    faq: "Perguntas que os donos fazem mesmo",
    q1: "Precisamos de estar em casa?",
    a1: "Não. Uma caixa de chaves ou um vizinho chega. Enviamos uma foto quando fechamos.",
    q2: "Têm seguro?",
    a2: "Num trabalho a sério: sim, e o certificado fica nesta página. Esta demo só mostra o padrão.",
    q3: "E se a vaga escorregar?",
    a3: "Ligamos antes das 09:00. Pode mudar a visita uma vez sem custo.",
    footer: "Brightline · empresa de limpezas de ficção",
    formOk: "Orçamento anotado. Uma equipa a sério ligaria dentro de uma hora.",
    demo: "Aviso de demo",
    demoLink: "Faço sites assim"
  }
};

I18N.start(window.SITE_I18N);
