window.SITE_I18N = {
  en: {
    "title.home": "Brightline — home cleaning in Lisboa, priced in seconds",
    "desc.home": "Fictional home cleaning service in Lisboa, Oeiras, Cascais and Almada. Instant price, live booking, a 48-hour come-back promise.",
    skip: "Skip to content",
    topbar: "Call or WhatsApp, 8:00–20:00",
    lang: "Language",
    menu: "Menu",
    navIncluded: "What's included",
    navAreas: "Areas",
    navReviews: "Reviews",
    navFaq: "FAQ",
    bookNow: "Book",
    rating: "4.9 from 1,240 cleans",
    heroTitle: "A spotless home, <span>priced in ten seconds.</span>",
    heroLede: "Vetted, insured cleaners who bring everything. Tell us about your home and see the price straight away — no calls, no surprises.",
    tick1: "Same crew every visit",
    tick2: "Eco products included",
    tick3: "Not right? We come back free within 48 h",
    quoteTitle: "Your price",
    qService: "Service",
    qHome: "Home size",
    qOffice: "Office size",
    qBaths: "Bathrooms",
    fewerBaths: "Fewer bathrooms",
    moreBaths: "More bathrooms",
    qFreq: "How often",
    qExtras: "Extras",
    bookThis: "Book this clean",
    "sv.standard": "Regular",
    "sv.deep": "Deep",
    "sv.moveout": "Move-out",
    "sv.office": "Office",
    "h.t0": "Studio (T0)",
    "h.t1": "1 bedroom (T1)",
    "h.t2": "2 bedrooms (T2)",
    "h.t3": "3 bedrooms (T3)",
    "h.t4": "4+ bedrooms (T4)",
    "h.o1": "Up to 80 m²",
    "h.o2": "80–150 m²",
    "h.o3": "150–300 m²",
    "f.once": "One-off",
    "f.weekly": "Weekly",
    "f.fortnight": "Every 2 weeks",
    "f.monthly": "Monthly",
    off: "−{n}%",
    "x.oven": "Inside the oven",
    "x.fridge": "Inside the fridge",
    "x.windows": "Inside windows",
    "x.balcony": "Balcony",
    "x.ironing": "An hour of ironing",
    eur: "€{n}",
    perVisit: " per visit",
    oneOff: " one-off",
    meta: "{h} h of cleaning · {crew} · about {d} at your place",
    crew1: "1 cleaner",
    crewN: "{n} cleaners",
    dur: "{n} h",
    onlyOnce: "Move-out cleans are one-off.",
    stripAria: "Photos of recent cleans",
    alt1: "A tidy living room with a yellow armchair",
    alt2: "A clean white kitchen with fruit on the counter",
    alt3: "A bright bathroom with a glass shower",
    alt4: "A cleaner washing a window",
    includedKicker: "What's included",
    includedTitle: "Room by room, nothing vague",
    roomsAria: "Rooms",
    "r.kitchen": "Kitchen",
    "r.bathroom": "Bathroom",
    "r.bedroom": "Bedrooms",
    "r.living": "Living areas",
    task: "Task",
    yourPick: "your pick",
    howTitle: "How it works",
    s1: "Price it",
    s1d: "Ten seconds, on this page. The price you see is the price you pay.",
    s2: "Pick a window",
    s2d: "Mornings, midday or afternoons, six days a week.",
    s3: "Come home to it",
    s3d: "We text when we arrive and send a photo when we leave.",
    areasKicker: "Areas",
    areasTitle: "Do we clean near you?",
    areasText: "Lisboa, Oeiras, Cascais and Almada. Type a postcode or a neighbourhood.",
    postcode: "Postcode or neighbourhood",
    postcodePh: "1200-000 or Alvalade",
    check: "Check",
    areaYes: "Yes — {zone} is ours. No travel fee.",
    areaFee: "Yes — {zone}, with a {fee} travel fee added to the booking.",
    areaSoon: "Not yet — we start in {zone} soon.",
    areaNo: "Sorry, we don't reach that postcode yet.",
    areaBad: "Type a postcode like 1200-000, or a neighbourhood name.",
    feeFree: "no travel fee",
    feeSoon: "soon",
    bookKicker: "Book",
    bookTitle: "Pick a day and a window",
    bookText: "Your quote comes with you. Change anything above and the price here follows.",
    day: "Day",
    window: "Arrival window",
    "w.am": "Morning",
    "w.mid": "Midday",
    "w.pm": "Afternoon",
    wFree: "{n} cleaners free",
    wLast: "Just enough",
    wFull: "Full",
    wSmall: "Needs {n} cleaners",
    fName: "Name",
    fPhone: "Phone",
    fAddress: "Address",
    sumService: "Service",
    sumHome: "Size",
    sumFreq: "How often",
    sumExtras: "Extras",
    sumNone: "None",
    sumFee: "Travel fee",
    sumTotal: "Each visit",
    editQuote: "Edit quote",
    bookFor: "Book for {price}",
    errDay: "Pick a day.",
    errWindow: "Pick an arrival window.",
    errFull: "That window just filled up — pick another.",
    errName: "Please add your name.",
    errPhone: "Please add a phone number we can text.",
    errAddress: "Please add the address.",
    errArea: "Check your postcode in Areas first — we may not reach it yet.",
    booked: "Booked — {code}. We'll text you the evening before.",
    mineTitle: "Your bookings",
    nextVisits: "Next: {list}",
    "st.booked": "Booked",
    "st.today": "Today",
    "st.done": "Done",
    cancel: "Cancel",
    stickyCta: "{price} · Book",
    reviewsKicker: "Reviews",
    reviewsTitle: "Homes we look after",
    guaranteeTitle: "The 48-hour promise",
    guaranteeText: "If anything on the checklist isn't right, tell us within 48 hours and we come back to fix it. Free, no forms.",
    faqKicker: "FAQ",
    faqTitle: "Before you book",
    footerLine: "A fictional cleaning company. Prices and reviews are examples.",
    backAtelier: "More demos",
    d0: "Sun", d1: "Mon", d2: "Tue", d3: "Wed", d4: "Thu", d5: "Fri", d6: "Sat",
    m0: "Jan", m1: "Feb", m2: "Mar", m3: "Apr", m4: "May", m5: "Jun", m6: "Jul", m7: "Aug", m8: "Sep", m9: "Oct", m10: "Nov", m11: "Dec"
  },
  pt: {
    "title.home": "Brightline — limpezas em Lisboa, com preço em segundos",
    "desc.home": "Serviço de limpeza doméstica fictício em Lisboa, Oeiras, Cascais e Almada. Preço imediato, marcação em tempo real e a promessa de voltar em 48 horas.",
    skip: "Saltar para o conteúdo",
    topbar: "Ligue ou envie WhatsApp, 8:00–20:00",
    lang: "Idioma",
    menu: "Menu",
    navIncluded: "O que inclui",
    navAreas: "Zonas",
    navReviews: "Opiniões",
    navFaq: "Perguntas",
    bookNow: "Marcar",
    rating: "4,9 em 1240 limpezas",
    heroTitle: "Uma casa impecável, <span>com preço em dez segundos.</span>",
    heroLede: "Profissionais verificados e com seguro, que levam tudo. Diga-nos como é a sua casa e veja logo o preço — sem chamadas, sem surpresas.",
    tick1: "A mesma equipa em todas as visitas",
    tick2: "Produtos ecológicos incluídos",
    tick3: "Não ficou bem? Voltamos sem custo em 48 h",
    quoteTitle: "O seu preço",
    qService: "Serviço",
    qHome: "Tipologia",
    qOffice: "Área do escritório",
    qBaths: "Casas de banho",
    fewerBaths: "Menos casas de banho",
    moreBaths: "Mais casas de banho",
    qFreq: "Frequência",
    qExtras: "Extras",
    bookThis: "Marcar esta limpeza",
    "sv.standard": "Regular",
    "sv.deep": "Profunda",
    "sv.moveout": "Mudança",
    "sv.office": "Escritório",
    "h.t0": "Estúdio (T0)",
    "h.t1": "T1",
    "h.t2": "T2",
    "h.t3": "T3",
    "h.t4": "T4 ou maior",
    "h.o1": "Até 80 m²",
    "h.o2": "80–150 m²",
    "h.o3": "150–300 m²",
    "f.once": "Pontual",
    "f.weekly": "Semanal",
    "f.fortnight": "Quinzenal",
    "f.monthly": "Mensal",
    off: "−{n}%",
    "x.oven": "Interior do forno",
    "x.fridge": "Interior do frigorífico",
    "x.windows": "Vidros por dentro",
    "x.balcony": "Varanda",
    "x.ironing": "Uma hora a passar a ferro",
    eur: "{n} €",
    perVisit: " por visita",
    oneOff: " pontual",
    meta: "{h} h de limpeza · {crew} · cerca de {d} em sua casa",
    crew1: "1 profissional",
    crewN: "{n} profissionais",
    dur: "{n} h",
    onlyOnce: "As limpezas de mudança são pontuais.",
    stripAria: "Fotografias de limpezas recentes",
    alt1: "Uma sala arrumada com um cadeirão amarelo",
    alt2: "Uma cozinha branca limpa com fruta na bancada",
    alt3: "Uma casa de banho clara com resguardo de vidro",
    alt4: "Uma profissional a limpar uma janela",
    includedKicker: "O que inclui",
    includedTitle: "Divisão a divisão, nada vago",
    roomsAria: "Divisões",
    "r.kitchen": "Cozinha",
    "r.bathroom": "Casa de banho",
    "r.bedroom": "Quartos",
    "r.living": "Sala e corredores",
    task: "Tarefa",
    yourPick: "a sua escolha",
    howTitle: "Como funciona",
    s1: "Veja o preço",
    s1d: "Dez segundos, nesta página. O preço que vê é o preço que paga.",
    s2: "Escolha um horário",
    s2d: "Manhã, hora de almoço ou tarde, seis dias por semana.",
    s3: "Chegue a casa",
    s3d: "Enviamos mensagem quando chegamos e uma fotografia quando saímos.",
    areasKicker: "Zonas",
    areasTitle: "Limpamos perto de si?",
    areasText: "Lisboa, Oeiras, Cascais e Almada. Escreva um código postal ou um bairro.",
    postcode: "Código postal ou bairro",
    postcodePh: "1200-000 ou Alvalade",
    check: "Verificar",
    areaYes: "Sim — {zone} é connosco. Sem taxa de deslocação.",
    areaFee: "Sim — {zone}, com uma taxa de deslocação de {fee} na marcação.",
    areaSoon: "Ainda não — começamos em {zone} em breve.",
    areaNo: "Lamentamos, ainda não chegamos a esse código postal.",
    areaBad: "Escreva um código postal como 1200-000, ou o nome de um bairro.",
    feeFree: "sem taxa",
    feeSoon: "em breve",
    bookKicker: "Marcar",
    bookTitle: "Escolha o dia e o horário",
    bookText: "O orçamento vem consigo. Mude algo acima e o preço aqui acompanha.",
    day: "Dia",
    window: "Hora de chegada",
    "w.am": "Manhã",
    "w.mid": "Almoço",
    "w.pm": "Tarde",
    wFree: "{n} profissionais livres",
    wLast: "Mesmo à justa",
    wFull: "Cheio",
    wSmall: "Precisa de {n} pessoas",
    fName: "Nome",
    fPhone: "Telemóvel",
    fAddress: "Morada",
    sumService: "Serviço",
    sumHome: "Tamanho",
    sumFreq: "Frequência",
    sumExtras: "Extras",
    sumNone: "Nenhum",
    sumFee: "Deslocação",
    sumTotal: "Cada visita",
    editQuote: "Alterar orçamento",
    bookFor: "Marcar por {price}",
    errDay: "Escolha um dia.",
    errWindow: "Escolha uma hora de chegada.",
    errFull: "Esse horário acabou de encher — escolha outro.",
    errName: "Indique o seu nome.",
    errPhone: "Indique um telemóvel para mensagens.",
    errAddress: "Indique a morada.",
    errArea: "Verifique primeiro o código postal em Zonas — talvez ainda não cheguemos lá.",
    booked: "Marcado — {code}. Enviamos mensagem na véspera.",
    mineTitle: "As suas marcações",
    nextVisits: "Próximas: {list}",
    "st.booked": "Marcada",
    "st.today": "Hoje",
    "st.done": "Feita",
    cancel: "Cancelar",
    stickyCta: "{price} · Marcar",
    reviewsKicker: "Opiniões",
    reviewsTitle: "Casas de que cuidamos",
    guaranteeTitle: "A promessa das 48 horas",
    guaranteeText: "Se algo da lista não estiver bem, diga-nos em 48 horas e voltamos para resolver. Sem custo, sem formulários.",
    faqKicker: "Perguntas",
    faqTitle: "Antes de marcar",
    footerLine: "Uma empresa de limpezas fictícia. Preços e opiniões são exemplos.",
    backAtelier: "Mais demos",
    d0: "Dom", d1: "Seg", d2: "Ter", d3: "Qua", d4: "Qui", d5: "Sex", d6: "Sáb",
    m0: "jan", m1: "fev", m2: "mar", m3: "abr", m4: "mai", m5: "jun", m6: "jul", m7: "ago", m8: "set", m9: "out", m10: "nov", m11: "dez"
  }
};

I18N.start(window.SITE_I18N);
