/**
 * PULSE — motion portfolio template
 * Edit this file to swap people, copy, projects, brands and links.
 * Field-by-field guide: sites/pulse/README.md
 * Videos are optional: leave `src` empty and the site draws a pixel cover.
 */
(() => {
  const ptEn = (pt, en) => ({ pt, en });
  const V = (src, ar, cap) => ({ src: src || "", ar: ar || "16/9", cap, thumb: "" });

  window.SITE = {
    storage: "pulse",
    name: "Rui Vale",
    studio: "PULSE",
    mark: "PV",
    role: ptEn("Motion Designer", "Motion Designer"),
    rec: "PULSE_SHOWREEL_v1.aep · 1920×1080 · 25 fps",
    year: "2026",
    timezone: "Europe/Lisbon",
    clockPrefix: "PT",
    email: "ola@studiopulse.pt",
    creditHighlight: ["Rui Vale", "Inês Mar"],
    heroLines: [
      ["RUI VALE", 0.4],
      ["MOTION", 1],
      ["DESIGNER", 1]
    ],
    heroColors: ["#ef6a2e", "#1fc6e3", "#1fc6e3"],
    links: [
      { label: "LinkedIn ↗", href: "https://www.linkedin.com/" },
      { label: "Vimeo ↗", href: "https://vimeo.com/" },
      { label: "Behance ↗", href: "https://www.behance.net/" }
    ],
    facts: {
      base: "Portugal",
      now: "PULSE — studio independente"
    },
    people: [
      {
        name: "Rui Vale",
        role: ptEn("Motion / AE", "Motion / AE"),
        blurb: ptEn("Anima campanhas de marca, LED e social. Ritmo, sonoplastia e expressões.", "Brand, LED and social motion. Rhythm, sound design and expressions.")
      },
      {
        name: "Inês Mar",
        role: ptEn("Direção de arte", "Art direction"),
        blurb: ptEn("Identidades, frames de partida e sistemas visuais para ecrã.", "Identities, start frames and on-screen visual systems.")
      }
    ],
    brands: [
      { n: "Norte", h: 0.55 },
      { n: "Vela", h: 0.5 },
      { n: "Atlas Rail", h: 0.48 },
      { n: "Farol", h: 0.52 },
      { n: "Leme", h: 0.5 },
      { n: "Kite", h: 0.46 },
      { n: "Casa Leme", h: 0.42 },
      { n: "Buoy", h: 0.5 }
    ],
    filters: [
      ["all", ptEn("Tudo", "All")],
      ["brand", ptEn("Marca", "Brand")],
      ["2d", ptEn("2D", "2D")],
      ["mixed", ptEn("Mixed media", "Mixed media")],
      ["ai", ptEn("IA", "AI")],
      ["social", ptEn("Social", "Social")],
      ["led", ptEn("LED / OOH", "LED / OOH")]
    ],
    caps: [
      [ptEn("Animação de marca", "Brand motion"), "After Effects · Illustrator"],
      [ptEn("Infografia 2D", "2D infographics"), "Data · Explainers"],
      [ptEn("Mixed media", "Mixed media"), "Archive · Collage"],
      [ptEn("Vídeo com IA", "AI video"), "Kling · Seedance · After Effects"],
      [ptEn("LED & OOH", "LED & OOH"), "Large format · Storefront"],
      [ptEn("Audio visualizers & som", "Audio visualizers & sound"), "Sound design · Expressions"]
    ],
    stickers: [
      { k: "badge", x: 0.9, y: 0.18, m: [0.86, 0], r: -10, c: "var(--yellow)", t: "var(--ink)" },
      { k: "curve", x: 0.88, y: 0.78, m: [0.72, 1], r: 4, c: "var(--cyan)", t: "var(--ink)" },
      { k: "ae", px: "ae", x: 0.09, y: 0.13, r: -8, c: "#00005b" },
      { k: "ai", px: "ai", x: 0.13, y: 0.93, r: 6, c: "#330000", nm: 1 },
      { k: "resolve", px: "resolve", round: 1, x: 0.72, y: 0.05, r: 0, c: "#3a3a3a", nm: 1 },
      { k: "claude", px: "claude", x: 0.37, y: 0.97, r: -5, c: "#f3eee4", nm: 1 },
      { k: "krea", px: "krea", x: 0.58, y: 0.98, r: 7, c: "#f5f5f5", nm: 1 }
    ],
    eggs: [
      { id: "kf", ico: "◆", m: ptEn("Encontraste um keyframe perdido. Estava aqui desde a v1.", "You found a lost keyframe. It's been here since v1.") },
      { id: "undo", ico: "⌘Z", m: ptEn("Ctrl+Z ×47. Ninguém precisa de saber.", "Ctrl+Z ×47. Nobody needs to know.") },
      { id: "render", ico: "99%", m: ptEn("Render a 99%… há três horas.", "Render at 99%… for three hours.") },
      { id: "precomp", ico: "▣", m: ptEn("Uma pré-comp dentro de uma pré-comp dentro de uma pré-comp.", "A precomp inside a precomp inside a precomp.") },
      { id: "f9", ico: "F9", m: ptEn("F9: a resposta para quase tudo.", "F9: the answer to almost everything.") },
      { id: "null", ico: "ø", m: ptEn("Um Null Object com nome. Raro.", "A named Null Object. Rare.") },
      { id: "ram", ico: "8K", m: ptEn("Pré-visualização a 8K. O portátil agradece.", "8K preview. The laptop is thrilled.") }
    ],
    projects: [
      {
        slug: "norte",
        feat: true,
        title: "Norte",
        sub: ptEn("Encomendas B2B", "B2B orders"),
        client: "Norte Logistics",
        market: "Porto",
        year: "2025",
        c1: "#111111",
        c2: "#ececec",
        ac: "#f2f2f2",
        tags: ["brand", "2d"],
        videos: [V("", "16/9", ptEn("Filme principal", "Main film"))],
        brief: ptEn(
          "Transformar a lógica de uma cadeia de abastecimento numa linguagem visual a preto e branco, com fluxo e ritmo de armazém.",
          "Turn supply-chain logic into a black-and-white visual language — warehouse flow, set to a beat."
        ),
        role: ptEn(["Animação e composição em After Effects a partir do design de Inês Mar"], ["Animation and compositing in After Effects from Inês Mar's design"]),
        tools: ["After Effects", "Illustrator"],
        credits: [
          ["Studio", "PULSE"],
          ["Art dir.", "Inês Mar"],
          ["Motion", "Rui Vale"],
          ["Client", "Norte Logistics"]
        ]
      },
      {
        slug: "vela",
        feat: true,
        title: "Vela",
        sub: ptEn("Das origens ao porto", "From origin to harbour"),
        client: "Vela Café",
        market: "Lisboa",
        year: "2025",
        c1: "#a50f24",
        c2: "#efe6d8",
        ac: "#efe6d8",
        tags: ["brand", "mixed"],
        videos: [V("", "16/9", ptEn("Filme", "Film"))],
        brief: ptEn(
          "Um filme que mistura arquivo, ilustração e packshots para uma torrada nova — sem parecer catálogo.",
          "A film that mixes archive, illustration and packshots for a new roast — without looking like a catalogue."
        ),
        role: ptEn(["Motion em mixed media, em dupla com Inês Mar"], ["Mixed-media motion, co-animated with Inês Mar"]),
        tools: ["After Effects", "Photoshop"],
        credits: [
          ["Studio", "PULSE"],
          ["Art dir.", "Inês Mar"],
          ["Motion", "Rui Vale"],
          ["Copy", "Paulo Cruz"],
          ["Client", "Vela Café"]
        ]
      },
      {
        slug: "farol",
        title: "Farol",
        sub: ptEn("Lançamento de identidade", "Identity launch"),
        client: "Farol Habitação",
        market: "Faro",
        year: "2025",
        c1: "#c3ea4f",
        c2: "#0f3a3e",
        ac: "#c3ea4f",
        tags: ["brand", "2d"],
        videos: [V("", "16/9", ptEn("Vídeo de lançamento", "Launch video"))],
        brief: ptEn("Tipografia cinética e um sistema de sinalética animada para o rebrand de um promotor algarvio.", "Kinetic type and an animated wayfinding system for an Algarve developer's rebrand."),
        role: ptEn(["Animação da nova identidade"], ["Animated the new identity"]),
        tools: ["After Effects", "Illustrator"],
        credits: [
          ["Studio", "PULSE"],
          ["Design", "Inês Mar"],
          ["Motion", "Rui Vale"],
          ["Client", "Farol Habitação"]
        ]
      },
      {
        slug: "atlas",
        badge: ptEn("Breakdown", "Breakdown"),
        title: "Atlas",
        sub: ptEn("Breakdown do anúncio Mix", "Mix ad breakdown"),
        client: "Atlas Rail",
        market: "Madrid",
        year: "2025",
        c1: "#4a0c0d",
        c2: "#f7c51e",
        ac: "#f7c51e",
        tags: ["social", "2d"],
        videos: [V("", "16/9", "Breakdown")],
        brief: ptEn("Breakdown de um anúncio de produto para formatos verticais: packshots, transições e cortes para reels.", "A product-ad breakdown for vertical formats: packshots, transitions and reel cuts."),
        role: ptEn(["Animação de produto e packshots"], ["Product animation and packshots"]),
        tools: ["After Effects"],
        credits: [
          ["Studio", "PULSE"],
          ["Design", "Inês Mar"],
          ["Motion", "Rui Vale"],
          ["Client", "Atlas Rail"]
        ]
      },
      {
        slug: "kite",
        title: "Kite",
        sub: ptEn("Signature Blend", "Signature Blend"),
        client: "Kite Roasters",
        market: "Porto",
        year: "2025",
        c1: "#e6e9ee",
        c2: "#1d2633",
        ac: "#aeb8c6",
        tags: ["brand"],
        videos: [V("", "16/9", ptEn("Filme", "Film"))],
        brief: ptEn("Filme de produto para um blend de especialidade — luz, vapor e tipo.", "Product film for a specialty blend — light, steam and type."),
        role: [],
        tools: ["After Effects"],
        credits: [
          ["Motion", "Rui Vale"],
          ["Client", "Kite Roasters"]
        ]
      },
      {
        slug: "leme",
        title: "Leme",
        sub: ptEn("Pop-up de verão", "Summer pop-up"),
        client: "Leme Gelado",
        market: "Lisboa",
        year: "2025",
        c1: "#5b1e3a",
        c2: "#f6d3df",
        ac: "#f4abc2",
        tags: ["ai", "social"],
        videos: [V("", "4/5", "Pop-up")],
        brief: ptEn("Peças sociais para uma marca de gelado: stills e loops gerados com IA, acabados em AE.", "Social pieces for an ice-cream brand: AI stills and loops, finished in AE."),
        role: ptEn(["Geração de imagem e vídeo", "Montagem e acabamento"], ["Image and video generation", "Edit and finishing"]),
        tools: ["AI video", "After Effects"],
        credits: [
          ["Studio", "PULSE"],
          ["Motion", "Rui Vale"],
          ["Client", "Leme Gelado"]
        ]
      },
      {
        slug: "casa-tours",
        title: "Casa Leme — Tours",
        sub: ptEn("Visitas virtuais", "Virtual tours"),
        client: "Casa Leme",
        market: "Setúbal",
        year: "2026",
        c1: "#1e1e1e",
        c2: "#c7b98f",
        ac: "#c7b98f",
        tags: ["ai"],
        videos: [V("", "3/2", "Moradia"), V("", "5/4", "Herdade")],
        brief: ptEn("Visitas guiadas a duas casas, compostas a partir de frames de partida e geradas em pipeline de IA.", "Guided tours of two houses, built from start frames and an AI video pipeline."),
        role: ptEn(["Pipeline IA e composição em After Effects"], ["AI pipeline and After Effects compositing"]),
        tools: ["AI video", "After Effects"],
        credits: [
          ["Studio", "PULSE"],
          ["Motion", "Rui Vale"],
          ["Client", "Casa Leme"]
        ]
      },
      {
        slug: "casa-led",
        title: "Casa Leme — LED",
        sub: ptEn("Ecrãs de montra", "Storefront screens"),
        client: "Casa Leme",
        market: "Lisboa",
        year: "2026",
        c1: "#e6c77c",
        c2: "#232324",
        ac: "#e6c77c",
        tags: ["ai", "led"],
        videos: [V("", "4/5", ptEn("Maré", "Tide")), V("", "4/5", ptEn("Serra", "Ridge"))],
        brief: ptEn("Loops verticais para montra: paisagem, tipo e um slogan que cabe em 8 segundos.", "Vertical storefront loops: landscape, type and a slogan that fits in 8 seconds."),
        role: ptEn(["Geração e composição para o formato dos ecrãs"], ["Generation and compositing for the screen format"]),
        tools: ["AI video", "After Effects"],
        credits: [
          ["Studio", "PULSE"],
          ["Motion", "Rui Vale"],
          ["Copy", "Paulo Cruz"],
          ["Client", "Casa Leme"]
        ]
      }
    ],
    lab: [
      {
        slug: "clay",
        title: "Clay LipSync",
        c1: "#e9a46a",
        c2: "#2a1409",
        ac: "#e9a46a",
        ar: "1/1",
        d: ptEn("Retrato em plasticina com lip sync — um teste de timing e textura.", "A clay portrait with lip sync — a timing and texture test.")
      },
      {
        slug: "synth",
        title: "Grid Synth",
        c1: "#f4f4f4",
        c2: "#c40c0c",
        ac: "#3d6bff",
        ar: "16/9",
        d: ptEn("Audio visualizer em grelha, inspirado em cinema experimental.", "A grid audio visualizer, nodding to experimental cinema.")
      }
    ],
    i18n: {
      pt: {
        role: "Motion Designer",
        "nav.work": "Trabalho",
        "nav.about": "Sobre",
        "nav.contact": "Contacto",
        skip: "Saltar para o trabalho",
        lede: "Estúdio de motion em Portugal. Animamos campanhas de marca, social, OOH e LED — entre o After Effects e pipelines com IA.",
        "cta.work": "Ver trabalho ↓",
        "cta.contact": "Falar connosco",
        clients: "Clientes: Norte, Vela, Atlas Rail, Farol, Leme, Kite, Casa Leme, Buoy.",
        "eb.work": "Destaques",
        "eb.lab": "Projetos pessoais",
        "eb.about": "Sobre",
        "eb.caps": "Capacidades",
        "eb.people": "Equipa",
        "eb.contact": "Contacto",
        "work.h": "Trabalho",
        "view.grid": "Grelha",
        "view.list": "Lista",
        view: "Ver caso",
        vid: "vídeo",
        vids: "vídeos",
        "soon.s": "Em breve",
        feat: "Destaque",
        case: "Ver caso →",
        cw: "Curva de animação do site: muda o scroll e as animações",
        "cw.h1": "Alça de saída da curva (setas para mover)",
        "cw.h2": "Alça de entrada da curva (setas para mover)",
        badge: "ABERTO A PROPOSTAS ✦ ABERTO A PROPOSTAS ✦ ",
        "tip.a.h": "A curva do site",
        "tip.a.p": "Arrasta as bolinhas laranja. O scroll e as animações do site passam a seguir esta curva.",
        "tip.b.h": "Boa!",
        "tip.b.p": "Agora faz scroll e sente a diferença. Duplo clique repõe a curva.",
        "tip.x": "Fechar dica",
        "dock.tip": "A curva vem contigo. Muda-a quando quiseres.",
        tile: "Ladrilho solto",
        "egg.hint": "Há ladrilhos soltos pelo chão. Passa o rato por cima e levanta-os.",
        "egg.done": "Encontraste tudo! Modo recreio ligado: o chão todo às cores.",
        "rec.on": "Recreio ligado",
        "rec.off": "Recreio desligado",
        "lab.p": "Experiências fora do horário: não recomendado a pessoas com epilepsia fotossensível.",
        "about.h": "Sobre",
        "caps.h": "Fazemos",
        "people.h": "Quem faz",
        bio1: "A PULSE é um estúdio pequeno em Portugal. Trabalhamos com direção criativa, design e copy para levar campanhas do storyboard ao ecrã.",
        bio2: "Território: infografia 2D e animação de marca, mixed media, audio visualizers e vídeo com IA, finalizado em After Effects. Ritmo, som, e expressões que poupam horas.",
        "f.base": "Base",
        "f.now": "Agora",
        "f.lang": "Línguas",
        "f.langv": "Português, Inglês",
        "f.open": "Estado",
        "f.openv": "Aberto a novas oportunidades",
        "contact.h": "Vamos pôr<br>coisas a mexer.",
        copy: "Copiar email",
        copied: "Copiado ✓",
        foot: "Feito à mão, pixel a pixel.",
        top: "↑ Topo",
        close: "← Fechar",
        prev: "Projeto anterior",
        nextp: "Projeto seguinte",
        brief: "Brief",
        myrole: "O nosso papel",
        tools: "Ferramentas",
        credits: "Créditos",
        next: "Próximo projeto",
        watch: "Ver",
        "snd.on": "Ver com som",
        "snd.off": "Silenciar",
        soon: "Vídeo disponível em breve — adiciona um MP4 em js/data.js",
        open: "Abrir ↗",
        vimeo: "Ver no Vimeo ↗"
      },
      en: {
        role: "Motion Designer",
        "nav.work": "Work",
        "nav.about": "About",
        "nav.contact": "Contact",
        skip: "Skip to work",
        lede: "A motion studio in Portugal. We animate brand, social, OOH and LED campaigns — between After Effects and AI-driven pipelines.",
        "cta.work": "See work ↓",
        "cta.contact": "Get in touch",
        clients: "Clients: Norte, Vela, Atlas Rail, Farol, Leme, Kite, Casa Leme, Buoy.",
        "eb.work": "Highlights",
        "eb.lab": "Personal projects",
        "eb.about": "About",
        "eb.caps": "Capabilities",
        "eb.people": "Team",
        "eb.contact": "Contact",
        "work.h": "Work",
        "view.grid": "Grid",
        "view.list": "List",
        view: "View case",
        vid: "video",
        vids: "videos",
        "soon.s": "Coming soon",
        feat: "Featured",
        case: "View case →",
        cw: "Site animation curve: changes the scroll and the animations",
        "cw.h1": "Curve outgoing handle (arrow keys to move)",
        "cw.h2": "Curve incoming handle (arrow keys to move)",
        badge: "OPEN TO NEW WORK ✦ OPEN TO NEW WORK ✦ ",
        "tip.a.h": "The site's curve",
        "tip.a.p": "Drag the orange dots. The site's scroll and animations will follow this curve.",
        "tip.b.h": "Nice!",
        "tip.b.p": "Now scroll and feel the difference. Double-click resets the curve.",
        "tip.x": "Close tip",
        "dock.tip": "Your curve comes along. Change it any time.",
        tile: "Loose tile",
        "egg.hint": "Some floor tiles are loose. Hover over them and lift them up.",
        "egg.done": "You found everything! Playground mode on: the whole floor in colour.",
        "rec.on": "Playground on",
        "rec.off": "Playground off",
        "lab.p": "After-hours experiments: not recommended for people with photosensitive epilepsy.",
        "about.h": "About",
        "caps.h": "We do",
        "people.h": "The people",
        bio1: "PULSE is a small studio in Portugal. We work with creative direction, design and copy to take campaigns from storyboard to screen.",
        bio2: "Our ground: 2D infographics and brand motion, mixed media, audio visualizers and AI video, finished in After Effects. Rhythm, sound, and expressions that save hours.",
        "f.base": "Based in",
        "f.now": "Now",
        "f.lang": "Languages",
        "f.langv": "Portuguese, English",
        "f.open": "Status",
        "f.openv": "Open to new opportunities",
        "contact.h": "Let's make<br>things move.",
        copy: "Copy email",
        copied: "Copied ✓",
        foot: "Handmade, pixel by pixel.",
        top: "↑ Top",
        close: "← Close",
        prev: "Previous project",
        nextp: "Next project",
        brief: "Brief",
        myrole: "Our role",
        tools: "Tools",
        credits: "Credits",
        next: "Next project",
        watch: "Play",
        "snd.on": "Play with sound",
        "snd.off": "Mute",
        soon: "Video coming soon — add an MP4 in js/data.js",
        open: "Open ↗",
        vimeo: "Watch on Vimeo ↗"
      }
    }
  };
})();
