window.SITE_I18N = {
  en: {
    "title.desk": "Aura Desk",
    "desc.desk": "Backoffice demo for the Aura salon: bookings, services, team, hours and site copy.",
    lang: "Language",
    loginTitle: "Good to see you",
    loginHint: "Demo account: user <b>demo</b>, password <b>demo</b>.",
    user: "User",
    pass: "Password",
    signIn: "Sign in",
    loginFail: "That isn't the demo login. Try demo / demo.",
    viewSite: "View the Aura site",
    backAtelier: "Atelier",
    resetDemo: "Reset demo data",
    resetAsk: "Reset all bookings, services, team, hours and copy to the demo defaults?",
    resetDone: "Demo data restored.",
    signOut: "Sign out",

    vToday: "Today",
    vRequests: "Requests",
    vBookings: "Bookings",
    vServices: "Services",
    vTeam: "Team",
    vHours: "Hours",
    vSite: "Site copy",

    hello: "Good day, Aura",
    newBooking: "New booking",
    schedule: "Schedule",
    today: "Today",
    tomorrow: "Tomorrow",
    prevDay: "Previous day",
    nextDay: "Next day",
    kToday: "Bookings today",
    kPending: "Waiting for you",
    kRevenue: "Expected today",
    kFree: "Free slots today",
    kFreeNote: "for a 45 min cut",
    closedDay: "Closed this day.",
    noBookingsDay: "Nothing booked yet.",

    guideTitle: "Try the demo",
    guideText: "The Aura site reads everything from this desk. Do these in any order and watch them tick.",
    g1: "Book something on the <a href=\"../aura/booking.html\" target=\"_blank\" rel=\"noopener\">Aura site</a> — it arrives here as a request",
    g2: "Accept or decline a request in <b>Requests</b>",
    g3: "Change a price or hide a service in <b>Services</b>",
    g4: "Edit the announcement in <b>Site copy</b>, then refresh the site",
    g5: "Close a day in <b>Hours</b> and see it go grey in booking",

    requestsTitle: "New booking requests",
    noRequests: "No requests waiting. New bookings from the Aura site land here.",
    accept: "Accept",
    decline: "Decline",
    accepted: "Confirmed {client} · {when}",
    declined: "Declined {client}'s request",
    newRequest: "New request: {client} · {service}",
    fromSite: "From the website",
    fromDesk: "Added at the desk",

    bookingsTitle: "All bookings",
    filterWhen: "When",
    upcoming: "Upcoming",
    past: "Past",
    all: "All",
    anyStatus: "Any status",
    status: "Status",
    search: "Search client or reference",
    noMatches: "No bookings match.",
    ref: "Ref",
    client: "Client",
    phone: "Phone",
    service: "Service",
    stylist: "Stylist",
    date: "Date",
    time: "Time",
    when: "When",
    note: "Note",
    actions: "Actions",
    "st.pending": "Pending",
    "st.confirmed": "Confirmed",
    "st.done": "Done",
    "st.cancelled": "Cancelled",
    markDone: "Mark done",
    confirm: "Confirm",
    cancelBooking: "Cancel",

    servicesTitle: "Services &amp; prices",
    servicesNote: "Changes save as you type and show on the Aura site straight away. Hidden services stay out of the menu and booking.",
    addService: "Add service",
    nameEn: "Name (EN)",
    namePt: "Name (PT)",
    category: "Category",
    price: "Price €",
    duration: "Minutes",
    visible: "On site",
    remove: "Remove",
    "cat.cut": "Cut",
    "cat.colour": "Colour",
    "cat.care": "Care",
    newService: "New service",
    removeServiceAsk: "Remove “{name}”? Existing bookings keep it.",

    teamTitle: "Who works when",
    addStaff: "Add stylist",
    name: "Name",
    roleEn: "Role (EN)",
    rolePt: "Role (PT)",
    worksOn: "Working days",
    does: "Services",
    colour: "Colour",
    newStylist: "New stylist",
    removeStaffAsk: "Remove {name} from the team?",

    hoursTitle: "Opening hours",
    hoursNote: "Booking only offers times inside these hours.",
    open: "Open",
    closed: "Closed",
    from: "From",
    to: "to",

    siteTitle: "What the website says",
    announcement: "Announcement bar",
    hero: "Headline",
    intro: "Intro",
    address: "Address",
    english: "English",
    portuguese: "Portuguese",
    saved: "Saved — the site has updated.",

    cancel: "Cancel",
    saveBooking: "Save booking",
    errClient: "Add the client's name.",
    errTime: "Pick a free time.",
    bookingSaved: "Booked {client} · {when}",
    noFreeTimes: "No free times",

    d0: "Sun", d1: "Mon", d2: "Tue", d3: "Wed", d4: "Thu", d5: "Fri", d6: "Sat",
    D0: "Sunday", D1: "Monday", D2: "Tuesday", D3: "Wednesday", D4: "Thursday", D5: "Friday", D6: "Saturday",
    months: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    vClients: "Clients",
    vInsights: "Insights",
    clientsTitle: "Who sits in the chair",
    clientsNote: "Built from every booking. Click a client to see their history or book them again.",
    cSearch: "Search name or phone",
    cName: "Client",
    cVisits: "Visits",
    cLast: "Last visit",
    cNext: "Next",
    cSpent: "Spent",
    cUsual: "Usually",
    never: "—",
    noClients: "No clients match.",
    cHistory: "History",
    bookAgain: "Book again",
    closePanel: "Close",
    cSince: "Client since {date}",
    cEvery: "Comes every {n} days on average",
    cNew: "First visit still to come",
    insightsTitle: "How the salon is doing",
    insightsNote: "Finished appointments from the last six weeks, plus what is booked ahead.",
    iRevenue: "Revenue",
    iVisits: "Appointments",
    iAvg: "Average ticket",
    iCancel: "Cancelled",
    iWeb: "Booked online",
    iWeekly: "Revenue per week",
    iTop: "Most booked services",
    iLoad: "Chair time booked this week",
    iLoadNote: "Booked minutes against working hours, Monday to Sunday.",
    iAhead: "Booked ahead",
    iAheadNote: "{n} appointments · {sum} € in the next 14 days",
    weekOf: "w/c {date}",
    weekLine: "{n} this week · {p}% booked",
    timeOff: "Time off",
    addOff: "Add",
    noOff: "No days off planned.",
    offAria: "Day off",
    offExists: "Already off that day.",
    offClosed: "That's not a working day anyway.",
    offClash: "{n} booking(s) that day — move them first."
  },
  pt: {
    "title.desk": "Aura Desk",
    "desc.desk": "Backoffice de demonstração do salão Aura: marcações, serviços, equipa, horário e textos do site.",
    lang: "Idioma",
    loginTitle: "Bom tê-la por cá",
    loginHint: "Conta de demonstração: utilizador <b>demo</b>, palavra-passe <b>demo</b>.",
    user: "Utilizador",
    pass: "Palavra-passe",
    signIn: "Entrar",
    loginFail: "Esse não é o acesso de demonstração. Experimente demo / demo.",
    viewSite: "Ver o site da Aura",
    backAtelier: "Atelier",
    resetDemo: "Repor dados de demonstração",
    resetAsk: "Repor todas as marcações, serviços, equipa, horário e textos para os valores de demonstração?",
    resetDone: "Dados de demonstração repostos.",
    signOut: "Sair",

    vToday: "Hoje",
    vRequests: "Pedidos",
    vBookings: "Marcações",
    vServices: "Serviços",
    vTeam: "Equipa",
    vHours: "Horário",
    vSite: "Textos do site",

    hello: "Bom dia, Aura",
    newBooking: "Nova marcação",
    schedule: "Agenda",
    today: "Hoje",
    tomorrow: "Amanhã",
    prevDay: "Dia anterior",
    nextDay: "Dia seguinte",
    kToday: "Marcações hoje",
    kPending: "À sua espera",
    kRevenue: "Previsto hoje",
    kFree: "Horas livres hoje",
    kFreeNote: "para um corte de 45 min",
    closedDay: "Fechado neste dia.",
    noBookingsDay: "Ainda sem marcações.",

    guideTitle: "Experimente a demo",
    guideText: "O site da Aura lê tudo desta desk. Faça estes passos por qualquer ordem e veja-os ficar marcados.",
    g1: "Marque algo no <a href=\"../aura/booking.html\" target=\"_blank\" rel=\"noopener\">site da Aura</a> — chega aqui como pedido",
    g2: "Aceite ou recuse um pedido em <b>Pedidos</b>",
    g3: "Mude um preço ou esconda um serviço em <b>Serviços</b>",
    g4: "Edite o anúncio em <b>Textos do site</b> e atualize o site",
    g5: "Feche um dia em <b>Horário</b> e veja-o ficar cinzento na marcação",

    requestsTitle: "Novos pedidos de marcação",
    noRequests: "Sem pedidos pendentes. As marcações feitas no site da Aura aparecem aqui.",
    accept: "Aceitar",
    decline: "Recusar",
    accepted: "Confirmada: {client} · {when}",
    declined: "Pedido de {client} recusado",
    newRequest: "Novo pedido: {client} · {service}",
    fromSite: "Pelo site",
    fromDesk: "Feita na desk",

    bookingsTitle: "Todas as marcações",
    filterWhen: "Quando",
    upcoming: "Próximas",
    past: "Passadas",
    all: "Todas",
    anyStatus: "Qualquer estado",
    status: "Estado",
    search: "Procurar cliente ou referência",
    noMatches: "Nenhuma marcação corresponde.",
    ref: "Ref.",
    client: "Cliente",
    phone: "Telemóvel",
    service: "Serviço",
    stylist: "Cabeleireiro/a",
    date: "Data",
    time: "Hora",
    when: "Quando",
    note: "Nota",
    actions: "Ações",
    "st.pending": "Pendente",
    "st.confirmed": "Confirmada",
    "st.done": "Concluída",
    "st.cancelled": "Cancelada",
    markDone: "Concluir",
    confirm: "Confirmar",
    cancelBooking: "Cancelar",

    servicesTitle: "Serviços e preços",
    servicesNote: "As alterações gravam-se enquanto escreve e aparecem logo no site da Aura. Serviços escondidos não aparecem no menu nem na marcação.",
    addService: "Adicionar serviço",
    nameEn: "Nome (EN)",
    namePt: "Nome (PT)",
    category: "Categoria",
    price: "Preço €",
    duration: "Minutos",
    visible: "No site",
    remove: "Remover",
    "cat.cut": "Corte",
    "cat.colour": "Cor",
    "cat.care": "Cuidados",
    newService: "Novo serviço",
    removeServiceAsk: "Remover “{name}”? As marcações existentes mantêm-no.",

    teamTitle: "Quem trabalha quando",
    addStaff: "Adicionar pessoa",
    name: "Nome",
    roleEn: "Função (EN)",
    rolePt: "Função (PT)",
    worksOn: "Dias de trabalho",
    does: "Serviços",
    colour: "Cor",
    newStylist: "Nova pessoa",
    removeStaffAsk: "Remover {name} da equipa?",

    hoursTitle: "Horário",
    hoursNote: "A marcação só oferece horas dentro deste horário.",
    open: "Aberto",
    closed: "Fechado",
    from: "Das",
    to: "às",

    siteTitle: "O que o site diz",
    announcement: "Barra de anúncio",
    hero: "Título",
    intro: "Introdução",
    address: "Morada",
    english: "Inglês",
    portuguese: "Português",
    saved: "Guardado — o site já foi atualizado.",

    cancel: "Cancelar",
    saveBooking: "Guardar marcação",
    errClient: "Indique o nome do cliente.",
    errTime: "Escolha uma hora livre.",
    bookingSaved: "Marcado: {client} · {when}",
    noFreeTimes: "Sem horas livres",

    d0: "Dom", d1: "Seg", d2: "Ter", d3: "Qua", d4: "Qui", d5: "Sex", d6: "Sáb",
    D0: "domingo", D1: "segunda", D2: "terça", D3: "quarta", D4: "quinta", D5: "sexta", D6: "sábado",
    months: "jan,fev,mar,abr,mai,jun,jul,ago,set,out,nov,dez",
    vClients: "Clientes",
    vInsights: "Números",
    clientsTitle: "Quem se senta na cadeira",
    clientsNote: "Construído a partir de todas as marcações. Clique num cliente para ver o histórico ou marcar de novo.",
    cSearch: "Pesquisar nome ou telemóvel",
    cName: "Cliente",
    cVisits: "Visitas",
    cLast: "Última visita",
    cNext: "Próxima",
    cSpent: "Gasto",
    cUsual: "Costuma fazer",
    never: "—",
    noClients: "Nenhum cliente corresponde.",
    cHistory: "Histórico",
    bookAgain: "Marcar de novo",
    closePanel: "Fechar",
    cSince: "Cliente desde {date}",
    cEvery: "Vem, em média, a cada {n} dias",
    cNew: "A primeira visita ainda está para vir",
    insightsTitle: "Como está a correr o salão",
    insightsNote: "Marcações concluídas nas últimas seis semanas, mais o que está marcado para a frente.",
    iRevenue: "Faturação",
    iVisits: "Marcações",
    iAvg: "Valor médio",
    iCancel: "Canceladas",
    iWeb: "Marcadas online",
    iWeekly: "Faturação por semana",
    iTop: "Serviços mais marcados",
    iLoad: "Tempo de cadeira marcado esta semana",
    iLoadNote: "Minutos marcados face às horas de trabalho, de segunda a domingo.",
    iAhead: "Marcado para a frente",
    iAheadNote: "{n} marcações · {sum} € nos próximos 14 dias",
    weekOf: "sem. {date}",
    weekLine: "{n} esta semana · {p}% ocupado",
    timeOff: "Folgas",
    addOff: "Juntar",
    noOff: "Sem folgas marcadas.",
    offAria: "Dia de folga",
    offExists: "Já está de folga nesse dia.",
    offClosed: "Esse já não é dia de trabalho.",
    offClash: "{n} marcação(ões) nesse dia — mude-as primeiro."
  }
};

I18N.start(window.SITE_I18N);
