window.SITE_I18N = {
  en: {
    title: "Aura Desk — backoffice",
    desc: "Demo admin for the Aura salon. Login demo / demo. Edits write to the same store the public site reads.",
    skip: "Skip to desk",
    lang: "Language",
    eyebrow: "Aura Desk",
    sign: "Sign in to the floor.",
    creds: "Demo credentials: <code>demo</code> / <code>demo</code>",
    user: "User",
    pass: "Password",
    enter: "Enter",
    dash: "Dashboard",
    bookings: "Bookings",
    services: "Services",
    staff: "Staff",
    hours: "Hours",
    copy: "Site copy",
    public: "View public site",
    logout: "Log out",
    today: "Today",
    next: "Next bookings",
    confirmed: "Confirmed",
    live: "Services live",
    when: "When",
    client: "Client",
    service: "Service",
    status: "Status",
    update: "Update",
    name: "Name",
    price: "Price",
    min: "Min",
    visible: "Visible",
    on: "On",
    hidden: "Hidden",
    remove: "Remove",
    role: "Role",
    days: "Days",
    add: "Add",
    saveHours: "Save hours",
    announce: "Announcement",
    hero: "Hero line",
    saveCopy: "Save copy",
    mon: "Monday", tue: "Tuesday", wed: "Wednesday", thu: "Thursday",
    fri: "Friday", sat: "Saturday", sun: "Sunday",
    stConfirmed: "confirmed",
    stDone: "done",
    stCancelled: "cancelled",
    loginFail: "Use demo / demo for this showcase.",
    hoursOk: "Hours saved. Refresh Aura to see them.",
    copyOk: "Copy saved. Open Aura and refresh.",
    demo: "Demo notice",
    demoLink: "I build sites like this"
  },
  pt: {
    title: "Aura Desk — backoffice",
    desc: "Administração demo do cabeleireiro Aura. Entrada demo / demo. As alterações escrevem no mesmo arquivo que o site público lê.",
    skip: "Saltar para a secretária",
    lang: "Idioma",
    eyebrow: "Aura Desk",
    sign: "Entre no piso.",
    creds: "Credenciais demo: <code>demo</code> / <code>demo</code>",
    user: "Utilizador",
    pass: "Palavra-passe",
    enter: "Entrar",
    dash: "Painel",
    bookings: "Marcações",
    services: "Serviços",
    staff: "Equipa",
    hours: "Horário",
    copy: "Textos do site",
    public: "Ver o site público",
    logout: "Sair",
    today: "Hoje",
    next: "Próximas marcações",
    confirmed: "Confirmadas",
    live: "Serviços no ar",
    when: "Quando",
    client: "Cliente",
    service: "Serviço",
    status: "Estado",
    update: "Alterar",
    name: "Nome",
    price: "Preço",
    min: "Min",
    visible: "Visível",
    on: "Activo",
    hidden: "Oculto",
    remove: "Remover",
    role: "Função",
    days: "Dias",
    add: "Acrescentar",
    saveHours: "Guardar horário",
    announce: "Aviso",
    hero: "Frase de abertura",
    saveCopy: "Guardar textos",
    mon: "Segunda", tue: "Terça", wed: "Quarta", thu: "Quinta",
    fri: "Sexta", sat: "Sábado", sun: "Domingo",
    stConfirmed: "confirmada",
    stDone: "feita",
    stCancelled: "cancelada",
    loginFail: "Use demo / demo nesta apresentação.",
    hoursOk: "Horário guardado. Actualize a Aura para o ver.",
    copyOk: "Textos guardados. Abra a Aura e actualize.",
    demo: "Aviso de demo",
    demoLink: "Faço sites assim"
  }
};

I18N.start(window.SITE_I18N);
