window.SITE_I18N = {
  en: {
    "title.home": "Aura — hair with a point of view",
    "title.services": "Services — Aura",
    "title.team": "Team — Aura",
    "title.gallery": "Gallery — Aura",
    "title.booking": "Book — Aura",
    "title.contact": "Contact — Aura",
    desc: "Fictional salon in Lisboa. Cuts, colour, booking. Prices live from the demo desk.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    navHome: "Home",
    navServices: "Services",
    navTeam: "Team",
    navGallery: "Gallery",
    navBook: "Book",
    navContact: "Contact",
    announceDefault: "New guests: first cut includes a consult.",
    heroDefault: "Hair with a point of view.",
    place: "Chiado · Lisboa",
    lede: "A small floor, three chairs, and colour that does not shout unless you ask it to.",
    book: "Book a chair",
    prices: "See prices",
    today: "Today on the floor",
    todayCopy: "Walk-ins after 16:00 if a chair frees. Otherwise write us a time.",
    callDesk: "Call the desk",
    hours: "Hours",
    menuTitle: "The menu.",
    menuLede: "Change a price in <a href=\"../aura-desk/\">Aura Desk</a> and refresh this page.",
    chairs: "Three chairs.",
    chairsLede: "Ask for a person when you book. Days live on the desk.",
    recent: "Recent work.",
    take: "Take a chair.",
    name: "Name",
    service: "Service",
    date: "Date",
    time: "Time",
    hold: "Hold it",
    find: "Find us.",
    message: "Message",
    send: "Send",
    footer: "Aura · fictional salon",
    openDesk: "Open the desk",
    demo: "Demo notice",
    demoLink: "I build sites like this",
    mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun",
    closed: "Closed",
    svcCut: "Cut & finish",
    svcBlow: "Blow-dry",
    svcBalayage: "Balayage",
    svcGloss: "Gloss",
    svcTreatment: "Repair ritual",
    roleColour: "Colour",
    roleCut: "Cut",
    roleTexture: "Texture",
    bookOk: "Booked on the demo desk. Open Aura Desk to see it.",
    contactOk: "Message kept on this page. A live salon would read it."
  },
  pt: {
    "title.home": "Aura — cabelo com ponto de vista",
    "title.services": "Serviços — Aura",
    "title.team": "Equipa — Aura",
    "title.gallery": "Galeria — Aura",
    "title.booking": "Marcar — Aura",
    "title.contact": "Contacto — Aura",
    desc: "Cabeleireiro de ficção em Lisboa. Cortes, cor, marcações. Preços ao vivo a partir da secretária demo.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    navHome: "Início",
    navServices: "Serviços",
    navTeam: "Equipa",
    navGallery: "Galeria",
    navBook: "Marcar",
    navContact: "Contacto",
    announceDefault: "Novos clientes: o primeiro corte inclui consulta.",
    heroDefault: "Cabelo com ponto de vista.",
    place: "Chiado · Lisboa",
    lede: "Um piso pequeno, três cadeiras, e cor que não grita a não ser que peça.",
    book: "Marcar cadeira",
    prices: "Ver preços",
    today: "Hoje no piso",
    todayCopy: "Entradas sem marcação depois das 16:00 se libertar uma cadeira. Senão escreva-nos uma hora.",
    callDesk: "Ligar à secretária",
    hours: "Horário",
    menuTitle: "A ementa.",
    menuLede: "Mude um preço na <a href=\"../aura-desk/\">Aura Desk</a> e actualize esta página.",
    chairs: "Três cadeiras.",
    chairsLede: "Peça uma pessoa ao marcar. Os dias vivem na secretária.",
    recent: "Trabalho recente.",
    take: "Sente-se.",
    name: "Nome",
    service: "Serviço",
    date: "Data",
    time: "Hora",
    hold: "Segurar",
    find: "Encontre-nos.",
    message: "Mensagem",
    send: "Enviar",
    footer: "Aura · cabeleireiro de ficção",
    openDesk: "Abrir a secretária",
    demo: "Aviso de demo",
    demoLink: "Faço sites assim",
    mon: "Seg", tue: "Ter", wed: "Qua", thu: "Qui", fri: "Sex", sat: "Sáb", sun: "Dom",
    closed: "Encerrado",
    svcCut: "Corte e modelação",
    svcBlow: "Brushing",
    svcBalayage: "Balayage",
    svcGloss: "Gloss",
    svcTreatment: "Ritual de reparação",
    roleColour: "Cor",
    roleCut: "Corte",
    roleTexture: "Textura",
    bookOk: "Marcado na secretária demo. Abra a Aura Desk para o ver.",
    contactOk: "Mensagem ficou nesta página. Um salão a sério lê-la-ia."
  }
};

I18N.start(window.SITE_I18N);
