window.SITE_I18N = {
  en: {
    "title.home": "Aura — hair with a point of view",
    "title.book": "Book — Aura",
    "desc.home": "Fictional salon in Chiado, Lisboa. Cuts, colour and care, with live booking.",
    "desc.book": "Book a cut, colour or treatment at Aura. Live availability.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    book: "Book",
    navServices: "Services",
    navTeam: "Team",
    navSalon: "The salon",
    navVisit: "Visit",
    place: "Chiado · Lisboa",
    bookVisit: "Book a visit",
    seePrices: "See prices",
    nextFree: "Next free cut",
    nextFreeText: "{day} at {time} with {name}",
    stamp: "three chairs · no rush",
    servicesEyebrow: "Menu",
    servicesTitle: "Services &amp; prices",
    servicesNote: "Prices include a wash and a finish. Long or very thick hair may add a little time.",
    "cat.cut": "Cut",
    "cat.colour": "Colour",
    "cat.care": "Care",
    min: "min",
    bookThis: "Book",
    teamEyebrow: "The team",
    teamTitle: "Three chairs, three specialists",
    bookWith: "Book with {name}",
    salonEyebrow: "The salon",
    salonTitle: "Daylight, quiet music, good coffee",
    galleryAria: "Photos of the salon",
    visitEyebrow: "Visit",
    visitTitle: "Find us in Chiado",
    hours: "Opening hours",
    closed: "Closed",
    openNow: "Open now · until {time}",
    closedNow: "Closed now · opens {day} at {time}",
    footerLine: "A fictional salon. Everything here is fed by the salon's own backoffice.",
    openDesk: "Open Aura Desk (demo / demo)",
    openDeskShort: "Open Aura Desk",
    backAtelier: "More demos",
    d0: "Sun", d1: "Mon", d2: "Tue", d3: "Wed", d4: "Thu", d5: "Fri", d6: "Sat",
    D0: "Sunday", D1: "Monday", D2: "Tuesday", D3: "Wednesday", D4: "Thursday", D5: "Friday", D6: "Saturday",
    months: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    today: "Today",
    tomorrow: "Tomorrow",

    bookEyebrow: "Booking",
    bookTitle: "Find a time that suits you",
    stepService: "Choose a service",
    stepStaff: "Who would you like?",
    stepDate: "Pick a day",
    stepTime: "Pick a time",
    stepDetails: "Your details",
    anyone: "First available",
    anyoneSub: "Whoever is free",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    noSlots: "Fully booked",
    noTimes: "No free times that day. Try another day or another stylist.",
    fName: "Name",
    fPhone: "Phone",
    fEmail: "Email (optional)",
    fNote: "Anything we should know?",
    sendRequest: "Send booking request",
    errName: "Please add your name.",
    errPhone: "Please add a phone number so we can confirm.",
    slotGone: "Sorry — that time was just taken. Please pick another.",
    summary: "Your visit",
    sumService: "Service",
    sumStaff: "With",
    sumWhen: "When",
    sumEmpty: "Choose a service to start.",
    total: "{price} € · about {min} min",
    doneEyebrow: "Request sent",
    doneTitle: "Thank you — it's with the salon",
    doneText: "We'll confirm by text message, usually within the hour. Keep your reference:",
    doneDemo: "Demo: open Aura Desk in another tab (demo / demo) and accept this request — the status here changes on its own.",
    bookAnother: "Book something else",
    status: "Status",
    "st.pending": "Waiting for the salon",
    "st.confirmed": "Confirmed",
    "st.done": "Completed",
    "st.cancelled": "Cancelled",
    lookupTitle: "Already booked?",
    lookupLabel: "Reference",
    lookupBtn: "Check status",
    lookupNone: "We couldn't find that reference.",
    lookupFound: "{service} · {when} · {status}"
  },
  pt: {
    "title.home": "Aura — cabelo com ponto de vista",
    "title.book": "Marcar — Aura",
    "desc.home": "Salão fictício no Chiado, Lisboa. Cortes, cor e cuidados, com marcação em tempo real.",
    "desc.book": "Marque um corte, cor ou tratamento na Aura. Disponibilidade em tempo real.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    book: "Marcar",
    navServices: "Serviços",
    navTeam: "Equipa",
    navSalon: "O salão",
    navVisit: "Visitar",
    place: "Chiado · Lisboa",
    bookVisit: "Marcar visita",
    seePrices: "Ver preços",
    nextFree: "Próximo corte livre",
    nextFreeText: "{day} às {time} com {name}",
    stamp: "três cadeiras · sem pressa",
    servicesEyebrow: "Menu",
    servicesTitle: "Serviços e preços",
    servicesNote: "Os preços incluem lavagem e acabamento. Cabelo comprido ou muito volumoso pode demorar um pouco mais.",
    "cat.cut": "Corte",
    "cat.colour": "Cor",
    "cat.care": "Cuidados",
    min: "min",
    bookThis: "Marcar",
    teamEyebrow: "A equipa",
    teamTitle: "Três cadeiras, três especialistas",
    bookWith: "Marcar com {name}",
    salonEyebrow: "O salão",
    salonTitle: "Luz natural, música baixa, bom café",
    galleryAria: "Fotografias do salão",
    visitEyebrow: "Visitar",
    visitTitle: "Estamos no Chiado",
    hours: "Horário",
    closed: "Fechado",
    openNow: "Aberto agora · até às {time}",
    closedNow: "Fechado agora · abre {day} às {time}",
    footerLine: "Um salão fictício. Tudo aqui vem do backoffice do próprio salão.",
    openDesk: "Abrir a Aura Desk (demo / demo)",
    openDeskShort: "Abrir a Aura Desk",
    backAtelier: "Mais demos",
    d0: "Dom", d1: "Seg", d2: "Ter", d3: "Qua", d4: "Qui", d5: "Sex", d6: "Sáb",
    D0: "domingo", D1: "segunda", D2: "terça", D3: "quarta", D4: "quinta", D5: "sexta", D6: "sábado",
    months: "jan,fev,mar,abr,mai,jun,jul,ago,set,out,nov,dez",
    today: "Hoje",
    tomorrow: "Amanhã",

    bookEyebrow: "Marcação",
    bookTitle: "Encontre uma hora que lhe dê jeito",
    stepService: "Escolha o serviço",
    stepStaff: "Com quem prefere?",
    stepDate: "Escolha o dia",
    stepTime: "Escolha a hora",
    stepDetails: "Os seus dados",
    anyone: "Primeira disponível",
    anyoneSub: "Quem estiver livre",
    morning: "Manhã",
    afternoon: "Tarde",
    evening: "Fim do dia",
    noSlots: "Esgotado",
    noTimes: "Não há horas livres nesse dia. Experimente outro dia ou outra pessoa.",
    fName: "Nome",
    fPhone: "Telemóvel",
    fEmail: "Email (opcional)",
    fNote: "Algo que devamos saber?",
    sendRequest: "Enviar pedido de marcação",
    errName: "Indique o seu nome.",
    errPhone: "Indique um telemóvel para podermos confirmar.",
    slotGone: "Pedimos desculpa — essa hora acabou de ser ocupada. Escolha outra.",
    summary: "A sua visita",
    sumService: "Serviço",
    sumStaff: "Com",
    sumWhen: "Quando",
    sumEmpty: "Escolha um serviço para começar.",
    total: "{price} € · cerca de {min} min",
    doneEyebrow: "Pedido enviado",
    doneTitle: "Obrigado — já está com o salão",
    doneText: "Confirmamos por SMS, normalmente dentro de uma hora. Guarde a sua referência:",
    doneDemo: "Demo: abra a Aura Desk noutro separador (demo / demo) e aceite este pedido — o estado aqui muda sozinho.",
    bookAnother: "Marcar outra coisa",
    status: "Estado",
    "st.pending": "A aguardar o salão",
    "st.confirmed": "Confirmada",
    "st.done": "Concluída",
    "st.cancelled": "Cancelada",
    lookupTitle: "Já tem marcação?",
    lookupLabel: "Referência",
    lookupBtn: "Ver estado",
    lookupNone: "Não encontrámos essa referência.",
    lookupFound: "{service} · {when} · {status}"
  }
};

I18N.start(window.SITE_I18N);
