window.SITE_I18N = {
  en: {
    "title.home": "Nido — bakery in Campo de Ourique",
    "desc.home": "Fictional neighbourhood bakery in Lisboa. Live tray, pre-order for pick-up, weekend classes and office breakfasts.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    navTray: "Today",
    navWeekends: "Weekends",
    navCatering: "Catering",
    navVisit: "Visit",
    basket: "Basket",
    openNow: "Open · until {time}",
    closedNow: "Closed · opens {day} {time}",
    kicker: "Campo de Ourique · since 2019",
    heroTitle: "Warm bread, <em>early.</em>",
    heroLede: "A small oven on a quiet corner. We bake through the morning and stop when the tray is empty — order ahead and yours waits on the shelf with your name on it.",
    heroCta: "See today's tray",
    heroVisit: "Find us",
    heroAlt: "Croissants dusted with sugar on a dark board",
    bakeTitle: "Out of the oven today",
    bakeDone: "out",
    bakeNext: "next",
    trayKicker: "The tray",
    trayTitle: "What's left right now",
    trayNote: "Counts update through the morning. Sold out today? Pre-order it for tomorrow.",
    left: "{n} left",
    soldOut: "Sold out at {time}",
    notYet: "From {time}",
    add: "Add",
    added: "Added",
    preorder: "Pre-order",
    "p.sourdough": "Country sourdough",
    "p.croissant": "Butter croissant",
    "p.cookie": "Brown butter cookie",
    "p.rye": "Seeded rye, sliced",
    "p.bun": "Cardamom bun",
    "p.coffee": "Flat white",
    "pd.sourdough": "48-hour dough, dark crust, 800 g.",
    "pd.croissant": "Laminated three days, Portuguese butter.",
    "pd.cookie": "Chewy middle, flaky salt on top.",
    "pd.rye": "Rye, sunflower and flax. Slices well for a week.",
    "pd.bun": "Knotted, sticky, a little too much cardamom.",
    "pd.coffee": "Our espresso blend, local milk.",
    weekendsKicker: "Weekends",
    weekendsTitle: "Flour on your sleeves",
    "e.kids": "Saturday dough hour",
    "e.kidsD": "Kids shape their own bun and take it home warm. Ages 5 to 10, a grown-up stays.",
    "e.bread": "Sourdough from scratch",
    "e.bread.d": "Two hours on starters, folding and scoring. You leave with a loaf and a jar of starter.",
    "e.cinnamon": "Sunday cinnamon list",
    "e.cinnamonD": "Add your name and we keep a box of four buns for you until noon.",
    spots: "{n} places left",
    full: "Full",
    join: "Add my name",
    joined: "You're on the list",
    leave: "Remove",
    cateringKicker: "Catering",
    cateringTitle: "Breakfast for the whole office",
    cateringText: "Boxes of pastries, bread, butter and fruit, delivered by eight. Tell us how many people and we'll do the maths.",
    cateringAlt: "A glass counter full of pastries",
    people: "People",
    boxAria: "Box",
    "box.light": "Light",
    "box.full": "Full",
    boxes: "Boxes",
    each: "per person",
    totalLabel: "Total",
    mix: "Mix",
    mixLine: "{c} pastries · {b} loaves · {f} fruit bowls",
    fCompany: "Company",
    fEmail: "Email",
    cateringSend: "Ask for this quote",
    errCompany: "Please add the company name.",
    errEmail: "Please add an email for the quote.",
    caterSent: "Thanks — a quote for {n} people is on its way. (Demo: nothing was sent.)",
    visitKicker: "Visit",
    visitAlt: "Round rustic loaves with wheat stalks",
    footerLine: "A fictional bakery. Photographs from Unsplash.",
    backAtelier: "More demos",
    basketTitle: "Your order",
    close: "Close",
    basketEmpty: "Nothing yet. Add something from the tray.",
    pickupDay: "Pick up",
    today: "Today",
    tomorrow: "Tomorrow",
    fName: "Name",
    fPhone: "Phone",
    total: "Total {sum} €",
    placeOrder: "Place order",
    errEmpty: "Your basket is empty.",
    errSlot: "Pick a time to collect.",
    errName: "Please add a name for the shelf.",
    errPhone: "Please add a phone number.",
    errStock: "Not enough {item} left today — try tomorrow.",
    ordered: "Order {code} placed. See you at {time}.",
    ordersTitle: "Your orders",
    "st.received": "Received",
    "st.oven": "In the oven",
    "st.ready": "On the shelf",
    "st.collected": "Collected",
    orderLine: "{code} · {when} {time} · {sum} €",
    remove: "Remove",
    d0: "Sun", d1: "Mon", d2: "Tue", d3: "Wed", d4: "Thu", d5: "Fri", d6: "Sat",
    D0: "Sunday", D1: "Monday", D2: "Tuesday", D3: "Wednesday", D4: "Thursday", D5: "Friday", D6: "Saturday"
  },
  pt: {
    "title.home": "Nido — padaria em Campo de Ourique",
    "desc.home": "Padaria de bairro fictícia em Lisboa. Tabuleiro em tempo real, encomendas para levantar, aulas ao fim-de-semana e pequenos-almoços para escritórios.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    navTray: "Hoje",
    navWeekends: "Fim-de-semana",
    navCatering: "Catering",
    navVisit: "Visitar",
    basket: "Cesto",
    openNow: "Aberto · até às {time}",
    closedNow: "Fechado · abre {day} às {time}",
    kicker: "Campo de Ourique · desde 2019",
    heroTitle: "Pão quente, <em>cedo.</em>",
    heroLede: "Um forno pequeno numa esquina sossegada. Cozemos durante a manhã e paramos quando o tabuleiro fica vazio — encomende antes e o seu fica na prateleira com o seu nome.",
    heroCta: "Ver o tabuleiro de hoje",
    heroVisit: "Onde estamos",
    heroAlt: "Croissants polvilhados com açúcar numa tábua escura",
    bakeTitle: "A sair do forno hoje",
    bakeDone: "saiu",
    bakeNext: "a seguir",
    trayKicker: "O tabuleiro",
    trayTitle: "O que ainda há agora",
    trayNote: "As quantidades atualizam ao longo da manhã. Esgotou hoje? Encomende para amanhã.",
    left: "Restam {n}",
    soldOut: "Esgotou às {time}",
    notYet: "A partir das {time}",
    add: "Juntar",
    added: "Junto",
    preorder: "Encomendar",
    "p.sourdough": "Pão de fermentação natural",
    "p.croissant": "Croissant de manteiga",
    "p.cookie": "Bolacha de manteiga tostada",
    "p.rye": "Centeio com sementes, fatiado",
    "p.bun": "Pão de cardamomo",
    "p.coffee": "Galão pequeno",
    "pd.sourdough": "Massa de 48 horas, côdea escura, 800 g.",
    "pd.croissant": "Folhado durante três dias, manteiga portuguesa.",
    "pd.cookie": "Centro macio, flor de sal por cima.",
    "pd.rye": "Centeio, girassol e linhaça. Fatia-se bem durante uma semana.",
    "pd.bun": "Em nó, peganhento, com cardamomo a mais.",
    "pd.coffee": "O nosso lote de expresso, leite local.",
    weekendsKicker: "Fim-de-semana",
    weekendsTitle: "Farinha nas mangas",
    "e.kids": "Hora da massa ao sábado",
    "e.kidsD": "As crianças moldam o seu pão e levam-no quente para casa. Dos 5 aos 10 anos, com um adulto.",
    "e.bread": "Fermentação natural do zero",
    "e.bread.d": "Duas horas de fermento, dobras e golpes. Sai com um pão e um frasco de fermento.",
    "e.cinnamon": "Lista da canela ao domingo",
    "e.cinnamonD": "Deixe o seu nome e guardamos uma caixa de quatro pães de canela até ao meio-dia.",
    spots: "Restam {n} lugares",
    full: "Cheio",
    join: "Juntar o meu nome",
    joined: "Está na lista",
    leave: "Retirar",
    cateringKicker: "Catering",
    cateringTitle: "Pequeno-almoço para o escritório inteiro",
    cateringText: "Caixas de bolos, pão, manteiga e fruta, entregues até às oito. Diga-nos quantas pessoas e nós fazemos as contas.",
    cateringAlt: "Um balcão de vidro cheio de bolos",
    people: "Pessoas",
    boxAria: "Caixa",
    "box.light": "Leve",
    "box.full": "Completa",
    boxes: "Caixas",
    each: "por pessoa",
    totalLabel: "Total",
    mix: "Composição",
    mixLine: "{c} bolos · {b} pães · {f} taças de fruta",
    fCompany: "Empresa",
    fEmail: "Email",
    cateringSend: "Pedir este orçamento",
    errCompany: "Indique o nome da empresa.",
    errEmail: "Indique um email para o orçamento.",
    caterSent: "Obrigado — o orçamento para {n} pessoas segue em breve. (Demo: nada foi enviado.)",
    visitKicker: "Visitar",
    visitAlt: "Pães redondos rústicos com espigas de trigo",
    footerLine: "Uma padaria fictícia. Fotografias do Unsplash.",
    backAtelier: "Mais demos",
    basketTitle: "A sua encomenda",
    close: "Fechar",
    basketEmpty: "Ainda nada. Junte algo do tabuleiro.",
    pickupDay: "Levantar",
    today: "Hoje",
    tomorrow: "Amanhã",
    fName: "Nome",
    fPhone: "Telemóvel",
    total: "Total {sum} €",
    placeOrder: "Fazer encomenda",
    errEmpty: "O cesto está vazio.",
    errSlot: "Escolha a hora de levantamento.",
    errName: "Indique um nome para a prateleira.",
    errPhone: "Indique um telemóvel.",
    errStock: "Já não há {item} suficiente hoje — experimente amanhã.",
    ordered: "Encomenda {code} feita. Até às {time}.",
    ordersTitle: "As suas encomendas",
    "st.received": "Recebida",
    "st.oven": "No forno",
    "st.ready": "Na prateleira",
    "st.collected": "Levantada",
    orderLine: "{code} · {when} {time} · {sum} €",
    remove: "Retirar",
    d0: "Dom", d1: "Seg", d2: "Ter", d3: "Qua", d4: "Qui", d5: "Sex", d6: "Sáb",
    D0: "domingo", D1: "segunda", D2: "terça", D3: "quarta", D4: "quinta", D5: "sexta", D6: "sábado"
  }
};

I18N.start(window.SITE_I18N);
