window.SITE_I18N = {
  en: {
    "title.home": "Nido — bread before the city wakes",
    "title.menu": "Menu — Nido",
    "title.events": "Weekends — Nido",
    "title.catering": "Catering — Nido",
    "title.contact": "Visit — Nido",
    desc: "Fictional bakery in Lisboa. Menu, hours, weekend lists, catering.",
    skip: "Skip to content",
    lang: "Language",
    menu: "Menu",
    navHome: "Home",
    navMenu: "Menu",
    navWeek: "Weekends",
    navCater: "Catering",
    navVisit: "Visit",
    kicker: "Open 07:00 · sold out by 13:00",
    hero: "Butter, flour, a little noise.",
    lede: "A fictional neighbourhood oven. Come early. The kouign-amann does not wait.",
    tray: "Today’s tray",
    hoursMap: "Hours &amp; map",
    morning: "Morning",
    morningCopy: "Country loaf, croissant, coffee that is not an afterthought.",
    weekend: "Weekend",
    weekendCopy: "Cinnamon lists, kids’ dough hour, the last focaccia at noon.",
    office: "Office",
    officeCopy: "Breakfast boxes. You write a headcount. We butter the rest.",
    trayTitle: "The tray.",
    bread: "Bread",
    vienno: "Viennoiserie",
    sweet: "Sweet",
    country: "Country loaf",
    rye: "Seeded rye",
    foca: "Olive focaccia",
    note: "vg vegetarian · gf gluten-free flour. Trays change when the oven says so.",
    satLists: "Saturday lists.",
    ev1t: "Cinnamon morning",
    ev1c: "A tray of rolls and a playlist that is older than the mixer.",
    ev2t: "Kids’ dough hour",
    ev2c: "Small hands, a lot of flour, one loaf to take home.",
    ev3t: "Harvest focaccia",
    ev3c: "Grapes, rosemary, the last of the summer oil.",
    room: "Breakfast for a room.",
    roomLede: "Boxes of pastry, a urn of coffee, bread that still argues. Forty-eight hours if you can.",
    name: "Name",
    head: "Headcount",
    date: "Date",
    noteL: "Note",
    notePh: "Office, wedding morning, no nuts.",
    askBox: "Ask for a box",
    nest: "The nest.",
    rest: "Tue–Sun · 07:00–13:00<br>Monday: the mixer rests.",
    footer: "Nido · fictional bakery",
    footLine: "Nido · Rua do Demo 3 · Tue–Sun 07–13",
    call: "Call",
    visit: "Visit",
    formOk: "The oven has your number. A live bakery would write back.",
    demo: "Demo notice",
    demoLink: "I build sites like this"
  },
  pt: {
    "title.home": "Nido — pão antes da cidade acordar",
    "title.menu": "Ementa — Nido",
    "title.events": "Fins-de-semana — Nido",
    "title.catering": "Catering — Nido",
    "title.contact": "Visitar — Nido",
    desc: "Padaria de ficção em Lisboa. Ementa, horário, listas de fim-de-semana, catering.",
    skip: "Saltar para o conteúdo",
    lang: "Idioma",
    menu: "Menu",
    navHome: "Início",
    navMenu: "Ementa",
    navWeek: "Fins-de-semana",
    navCater: "Catering",
    navVisit: "Visitar",
    kicker: "Abre às 07:00 · esgota às 13:00",
    hero: "Manteiga, farinha, um pouco de ruído.",
    lede: "Um forno de bairro de ficção. Venha cedo. O kouign-amann não espera.",
    tray: "O tabuleiro de hoje",
    hoursMap: "Horário e mapa",
    morning: "Manhã",
    morningCopy: "Pão de campanha, croissant, café que não é um resto.",
    weekend: "Fim-de-semana",
    weekendCopy: "Listas de canela, hora da massa para miúdos, a última focaccia ao meio-dia.",
    office: "Escritório",
    officeCopy: "Caixas de pequeno-almoço. Escreve a conta de cabeças. Nós manteigamos o resto.",
    trayTitle: "O tabuleiro.",
    bread: "Pão",
    vienno: "Viennoiserie",
    sweet: "Doce",
    country: "Pão de campanha",
    rye: "Centeio com sementes",
    foca: "Focaccia de azeitona",
    note: "vg vegetariano · gf farinha sem glúten. Os tabuleiros mudam quando o forno manda.",
    satLists: "Listas de sábado.",
    ev1t: "Manhã de canela",
    ev1c: "Um tabuleiro de enrolados e uma lista mais velha que a batedeira.",
    ev2t: "Hora da massa para miúdos",
    ev2c: "Mãos pequenas, muita farinha, um pão para levar.",
    ev3t: "Focaccia da colheita",
    ev3c: "Uvas, alecrim, o último azeite de verão.",
    room: "Pequeno-almoço para uma sala.",
    roomLede: "Caixas de pastelaria, um termo de café, pão que ainda discute. Quarenta e oito horas, se puder.",
    name: "Nome",
    head: "Pessoas",
    date: "Data",
    noteL: "Nota",
    notePh: "Escritório, manhã de casamento, sem frutos secos.",
    askBox: "Pedir uma caixa",
    nest: "O ninho.",
    rest: "Ter–Dom · 07:00–13:00<br>Segunda: a batedeira descansa.",
    footer: "Nido · padaria de ficção",
    footLine: "Nido · Rua do Demo 3 · Ter–Dom 07–13",
    call: "Ligar",
    visit: "Visitar",
    formOk: "O forno tem o seu número. Uma padaria a sério responderia.",
    demo: "Aviso de demo",
    demoLink: "Faço sites assim"
  }
};

I18N.start(window.SITE_I18N);
