// Generated from the string table in the build script: EN + PT-PT.
window.SITE_I18N = {
  "en": {
    "title.home": "Lucas Bastos • Freelance Designer & Developer",
    "title.work": "Work • Lucas Bastos",
    "title.about": "About • Lucas Bastos",
    "title.contact": "Contact • Lucas Bastos",
    "desc.home": "Lucas Bastos, freelance designer and developer in Lisbon.",
    "desc.work": "Selected projects by Lucas Bastos.",
    "desc.about": "About Lucas Bastos, freelance designer and developer.",
    "desc.contact": "Start a project with Lucas Bastos.",
    "skip": "Skip to content",
    "nav.home": "Home",
    "nav.work": "Work",
    "nav.about": "About",
    "nav.contact": "Contact",
    "navigation": "Navigation",
    "socials": "Socials",
    "language": "Language",
    "language.attr": "Language",
    "menu": "Menu",
    "menu.open.attr": "Open menu",
    "menu.close.attr": "Close menu",
    "menu.main.attr": "Main",
    "credit": "Code by Lucas",
    "view": "View",
    "photo": "Photo",
    "photo.group.attr": "Choose the hero photo",
    "hanger": "Located<br />in<br />Portugal",
    "caption": "Freelance<br />Designer &amp; Developer",
    "h1.home": "Lucas Bastos — freelance designer &amp; developer in Lisbon",
    "intro": "Websites for small, stubborn brands. Fast to load, calm to use and simple to keep up to date. Drawn in Lisbon, shipped anywhere.",
    "intro.side": "Design, code and motion under one roof, so nothing gets lost between the mockup and the browser.",
    "about.me": "About me",
    "recent": "Recent work",
    "more": "More work",
    "rows.attr": "More projects",
    "footer.title": "Let’s make<br />something",
    "touch": "Get in touch",
    "version": "Version",
    "edition": "2026 © Edition",
    "localtime": "Local time",
    "h1.work": "Work that had to earn its place",
    "th.client": "Client",
    "th.location": "Location",
    "th.services": "Services",
    "th.year": "Year",
    "svc.dd": "Design &amp; Development",
    "svc.id": "Interaction &amp; Development",
    "svc.td": "Type &amp; Development",
    "svc.d": "Development",
    "svc.ds": "Design",
    "loc.lisbon": "Lisbon",
    "h1.about": "Helping small brands sound like themselves online",
    "readmore.attr": "Read more",
    "about.lead": "I work with founders, studios and small teams who care how things feel, not only how they look. Most projects start with a conversation and a blank page, and end with a site the team can run on its own.",
    "about.small": "Always exploring",
    "about.img.attr": "A quiet studio window looking out over a misty city",
    "services.title": "I can help you with …",
    "s1.title": "Design",
    "s1.copy": "A clear visual direction, built for the screen first. Layout, type and motion decided together, so the site feels like one thing.",
    "s2.title": "Development",
    "s2.copy": "Hand-written, fast front ends with a CMS your team can actually use. Accessible by default, and easy to hand over.",
    "s3.title": "The full package",
    "s3.copy": "From the first sketch to launch day. One person on the whole project, so the details survive the trip from idea to browser.",
    "h1.contact": "Let’s start a project together",
    "f.name": "What’s your name?",
    "f.email": "What’s your email?",
    "f.org": "What’s the name of your organisation?",
    "f.services": "What services are you looking for?",
    "f.msg": "Your message",
    "ph.name.attr": "Ana Costa *",
    "ph.email.attr": "ana@costa.pt *",
    "ph.org.attr": "Costa & Filhos",
    "ph.services.attr": "Web design, development …",
    "ph.msg.attr": "Hello Lucas, can you help me with … *",
    "send": "Send it!",
    "contact.details": "Contact details",
    "business.details": "Business details",
    "business": "Lucas Bastos, design &amp; code<br />Location: Lisbon, PT",
    "form.missing": "Please fill in the fields marked with *.",
    "form.bademail": "That email address doesn’t look right.",
    "form.ok": "Thanks! This is a demo form, so nothing was sent. Connect a form service to receive messages.",
    "photo1.attr": "Photo 1",
    "photo2.attr": "Photo 2",
    "photo3.attr": "Photo 3",
    "photo4.attr": "Photo 4",
    "photo5.attr": "Photo 5",
    "photo6.attr": "Photo 6",
    "photo7.attr": "Photo 7"
  },
  "pt": {
    "title.home": "Lucas Bastos • Designer & Programador freelancer",
    "title.work": "Trabalho • Lucas Bastos",
    "title.about": "Sobre • Lucas Bastos",
    "title.contact": "Contacto • Lucas Bastos",
    "desc.home": "Lucas Bastos, designer e programador freelancer em Lisboa.",
    "desc.work": "Projetos selecionados de Lucas Bastos.",
    "desc.about": "Sobre Lucas Bastos, designer e programador freelancer.",
    "desc.contact": "Comece um projeto com Lucas Bastos.",
    "skip": "Saltar para o conteúdo",
    "nav.home": "Início",
    "nav.work": "Trabalho",
    "nav.about": "Sobre",
    "nav.contact": "Contacto",
    "navigation": "Navegação",
    "socials": "Redes sociais",
    "language": "Idioma",
    "language.attr": "Idioma",
    "menu": "Menu",
    "menu.open.attr": "Abrir menu",
    "menu.close.attr": "Fechar menu",
    "menu.main.attr": "Principal",
    "credit": "Código por Lucas",
    "view": "Ver",
    "photo": "Foto",
    "photo.group.attr": "Escolher a foto principal",
    "hanger": "Baseado<br />em<br />Portugal",
    "caption": "Freelancer<br />Designer &amp; Programador",
    "h1.home": "Lucas Bastos — designer e programador freelancer em Lisboa",
    "intro": "Sites para marcas pequenas e teimosas. Rápidos a carregar, calmos de usar e simples de manter atualizados. Desenhados em Lisboa, entregues em qualquer lado.",
    "intro.side": "Design, código e movimento sob o mesmo teto, para que nada se perca entre a maqueta e o browser.",
    "about.me": "Sobre mim",
    "recent": "Trabalho recente",
    "more": "Mais trabalho",
    "rows.attr": "Mais projetos",
    "footer.title": "Vamos criar<br />algo juntos",
    "touch": "Entrar em contacto",
    "version": "Versão",
    "edition": "Edição 2026 ©",
    "localtime": "Hora local",
    "h1.work": "Trabalho que teve de merecer o seu lugar",
    "th.client": "Cliente",
    "th.location": "Local",
    "th.services": "Serviços",
    "th.year": "Ano",
    "svc.dd": "Design e desenvolvimento",
    "svc.id": "Interação e desenvolvimento",
    "svc.td": "Tipografia e desenvolvimento",
    "svc.d": "Desenvolvimento",
    "svc.ds": "Design",
    "loc.lisbon": "Lisboa",
    "h1.about": "Ajudo marcas pequenas a soarem como elas próprias online",
    "readmore.attr": "Ler mais",
    "about.lead": "Trabalho com fundadores, estúdios e equipas pequenas que se importam com a forma como as coisas se sentem, não só com o aspeto. A maioria dos projetos começa com uma conversa e uma página em branco, e acaba com um site que a equipa consegue gerir sozinha.",
    "about.small": "Sempre a explorar",
    "about.img.attr": "Uma janela de estúdio tranquila sobre uma cidade com nevoeiro",
    "services.title": "Posso ajudar-te com …",
    "s1.title": "Design",
    "s1.copy": "Uma direção visual clara, pensada primeiro para o ecrã. Layout, tipografia e movimento decididos em conjunto, para que o site pareça uma só coisa.",
    "s2.title": "Desenvolvimento",
    "s2.copy": "Front-ends rápidos, escritos à mão, com um CMS que a tua equipa consegue mesmo usar. Acessíveis de raiz e fáceis de entregar.",
    "s3.title": "O pacote completo",
    "s3.copy": "Do primeiro esboço ao dia do lançamento. Uma só pessoa em todo o projeto, para que os detalhes sobrevivam à viagem da ideia ao browser.",
    "h1.contact": "Vamos começar um projeto juntos",
    "f.name": "Como te chamas?",
    "f.email": "Qual é o teu email?",
    "f.org": "Qual é o nome da tua organização?",
    "f.services": "Que serviços procuras?",
    "f.msg": "A tua mensagem",
    "ph.name.attr": "Ana Costa *",
    "ph.email.attr": "ana@costa.pt *",
    "ph.org.attr": "Costa & Filhos",
    "ph.services.attr": "Web design, desenvolvimento …",
    "ph.msg.attr": "Olá Lucas, podes ajudar-me com … *",
    "send": "Enviar!",
    "contact.details": "Contactos",
    "business.details": "Dados profissionais",
    "business": "Lucas Bastos, design e código<br />Local: Lisboa, PT",
    "form.missing": "Preenche os campos marcados com *.",
    "form.bademail": "Esse endereço de email não parece correto.",
    "form.ok": "Obrigado! Isto é um formulário de demonstração, por isso nada foi enviado. Liga um serviço de formulários para receber mensagens.",
    "photo1.attr": "Foto 1",
    "photo2.attr": "Foto 2",
    "photo3.attr": "Foto 3",
    "photo4.attr": "Foto 4",
    "photo5.attr": "Foto 5",
    "photo6.attr": "Foto 6",
    "photo7.attr": "Foto 7"
  }
};

I18N.start(window.SITE_I18N);
